### ISSUE TITLE
DateTime parse 1970-01-01 00:00:00 to 1970-01-01 06:28:16

### ISSUE THREAD

**Issue by CaiZhanqi** [yandex/ClickHouse#4605] opened 2019-03-06 01:43 UTC
**Describe the bug**
when I insert values to table I have catch it .
If the cloumn type is datetime and value is 1970-01-01 00:00:00, I insert it and do select I find that the value of 1970-01-01 00:00:00 has changed to 1970-01-01 06:28:16.

**How to reproduce**
* The version of ClickHouse server I am using is 18.14.8.

**SQL**
CREATE TABLE table_test ( appName String,  appVersion String,  http_host String,  log_time DateTime,  respond_num Int32,  respond_time Float32,  partition_date Date) ENGINE = Distributed(xxx_bigdata_cluster, realtime, table_test_local, cityHash64(appName))

insert into table_test values('6','','','1970-01-01 00:00:00',1,1,now());

**unexpected result**
select * from table_test;
┌─appName─┬─appVersion─┬─http_host─┬────────────log_time─┬─respond_num─┬─respond_time─┬─partition_date─┐
│ 6       │            │           │ 1970-01-01 06:28:16 │           1 │            1 │     2019-03-06 │
└─────────┴────────────┴───────────┴─────────────────────┴─────────────┴──────────────┴────────────────┘
**Expected behavior**
I expect that the value is what i inserted just like 1970-01-01 00:00:00 not 1970-01-01 06:28:16.

**Comment by CaiZhanqi** [comment] 2019-03-06 02:03
if value of insert is 1970-01-01 08:00:00 it will become to 0000-00-00 00:00:00

**Comment by den-crane** [comment] 2019-03-06 02:34
duplicate of 3470

**Closed** 2019-03-06 02:39 UTC
Labels: bug, issue
