### ISSUE TITLE
Windows: Clickhouse Fails on start with Poco::FileAccessDeniedException Error

### ISSUE THREAD

**Issue by Anamonty** [yandex/ClickHouse#6722] opened 2019-08-29 09:35 UTC
I'm trying to run Clickhouse on Ubuntu terminal on Windows 10. After reinstallation Clickhouse  fails to start with the tracelog:
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
terminate called after throwing an instance of 'Poco::FileAccessDeniedException'
terminate called recursively
Aborted (core dumped)
I've tried to change the permession for clickhouse folders but it didn't help.

When running sudo clickhouse-server --config-file=/etc/clickhouse-server/config.xml it gives the following error: 
2019.08.29 12:34:15.508088 [ 1 ] {} <Information> : Starting ClickHouse 19.13.3.26 with revision 54425
2019.08.29 12:34:15.508409 [ 1 ] {} <Information> Application: starting up
2019.08.29 12:34:15.513909 [ 2 ] {} <Error> BaseDaemon: ########################################
2019.08.29 12:34:15.514261 [ 2 ] {} <Error> BaseDaemon: (version 19.13.3.26 (official build)) (from thread 1) Received signal Aborted (6).
2019.08.29 12:34:15.515225 [ 2 ] {} <Error> BaseDaemon:
2019.08.29 12:34:15.515704 [ 2 ] {} <Error> BaseDaemon: 0. /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f166a85ee97]

Version: ClickHouse 19.13.3.26 with revision 54425

**Comment by filimonov** [comment] 2019-08-29 11:57
Duplicate of #6480 
Let's continue discussion there.

**Closed by filimonov** 2019-08-29 11:57 UTC
Labels: bug, duplicate
