### ISSUE TITLE
possible regression issue in array support

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#1362] opened 2017-10-16 14:14 UTC
Hello,

After I updated to  1.1.54298 I have the following issues with array's columns:

```sql
CREATE TABLE table_array4(`array_empty` Array(Nullable(Int64)), `partition` Date, `timestamp` DateTime) ENGINE = ReplicatedMergeTree('/var/lib/clickhouse/tables/{shard}/table_array4','{replica}',`partition`,`timestamp`,8192);
INSERT INTO table_array4(`timestamp`,`partition`,`array_empty`) VALUES (1508162579,17455,[1]);
INSERT INTO table_array4(`timestamp`,`partition`,`array_empty`) VALUES (1508162591,17455,[]);
SELECT array_empty from table_array4;
```

```sh
Code: 246, e.displayText() = DB::Exception: bad size of marks file `/var/lib/clickhouse/data/default/table_array4/20171016_20171016_1_1_0/array_empty.null.mrk':0, must be: 16: (while reading column array_empty): (while reading from part /var/lib/clickhouse/data/default/table_array4/20171016_20171016_1_1_0/ from mark 0 with max_rows_to_read = 8192), e.what() = DB::Exception
```

Seems after I insert an array with one element I'm not longer able to insert empty arrays.

Kind regards,
Silviu

**Comment by proller** [comment] 2017-10-16 18:31
Fixed in master.
this tests
```
DROP TABLE IF EXISTS test.table_array4;
CREATE TABLE test.table_array4(`array_empty` Array(Nullable(Int64)), `partition` Date, `timestamp` DateTime) ENGINE = ReplicatedMergeTree('/var/lib/clickhouse/tables/{shard}/table_array4','{replica}',`partition`,`timestamp`,8192);
INSERT INTO test.table_array4(`timestamp`,`partition`,`array_empty`) VALUES (1508162579,17455,[1]);
INSERT INTO test.table_array4(`timestamp`,`partition`,`array_empty`) VALUES (1508162591,17455,[]);
SELECT array_empty from test.table_array4;
DROP TABLE test.table_array4;
```
returns
```
[1]
[] 
```

**Comment by silviucpp** [comment] 2017-10-16 18:57
@proller very strange. I'm on the testing branch:

deb http://repo.yandex.ru/clickhouse/trusty testing main

And my server doesn't show any update available.  My server shows  1.1.54298 which is not last release (there are 2 others). I thought commits in master automatically generates updates available on this testing channel :)

Anyway I will wait for the new release and retest and close the issue if will not replicate any longer.

Silviu

**Comment by proller** [comment] 2017-10-16 19:16
This fix not released.
You can build unreleased code manually, but at current moment latests master have some bugs.

**Comment by silviucpp** [comment] 2017-10-16 20:00
@proller any idea if the fact that for a column of type :  Array(Nullable(Float64)) the default value is considered 0 and not NULL it's expected behavior ?

For example if you do:

```sql
SELECT array_field[4]  from table
```
where that element on that index is not existing you receive 0 instead NULL. Is this correct ?

**Comment by silviucpp** [comment] 2017-10-16 20:16
From documentation doesn't seems to be a bug but it's not a consistent behavior. 

What I mean is the default for Nullable(Float64) fields is NULL, for Float64 is 0 and for Array(Nullable(Float64)) it's also 0 not NULL as you are expecting.

**Comment by proller** [comment] 2017-10-17 13:25
Yes look as bug.
Will be fixed.

in current master just fixed table corruption "bad size of marks file"

**Comment by silviucpp** [comment] 2017-10-17 13:27
@proller  do you want to open a separate ticket for this bug with inconsistent default values ?

I see the one "bad size of marks file" it's already reported and tracked here : https://github.com/yandex/ClickHouse/issues/1282

I would like to close mine

**Comment by ztlpn** [comment] 2017-10-19 16:01
Yes, this is a duplicate of #1282 
Please open a separate issue concerning the default values.

**Closed by ztlpn** 2017-10-19 16:01 UTC
