### ISSUE TITLE
kafka engine with sasl plaintext + scram ... not work...

### ISSUE THREAD

**Issue by mcarbonneaux** [yandex/ClickHouse#3997] opened 2019-01-07 14:01 UTC
when kafka client start connexion to kafka they return this message:
```
 Application: DB::Exception: Failed to create consumer handle: No provider for SASL mechanism SCRAM-SHA-256: recompile librdkafka with libsasl2 or openssl support. Current build options: PLAIN
```

when i connect with other tool that support sasl plain text + scram authentification they work fine...

my clickhouse kafka config file:
```
    <kafka>
      <sasl_mechanism>SCRAM-SHA-256</sasl_mechanism>
      <security_protocol>sasl_plaintext</security_protocol>
      <sasl_username>producer_user_name</sasl_username>
      <sasl_password>producer_user_pass</sasl_password>
      <debug>all</debug>
    </kafka>
```

i think is the librdkafka compiled by clickhouse processus not compile with sasl_plaintext support...

i've compiled clickhouse with cmake from github source with submodule embeded... i'm on rhel7...

**Comment by mcarbonneaux** [comment] 2019-01-11 19:18
i think is because find_rdkafka.cmake not search sasl library if USE_INTERNAL_RDKAFKA_LIBRARY is set...

```
if (NOT USE_INTERNAL_RDKAFKA_LIBRARY)
    find_library (RDKAFKA_LIB rdkafka)
    find_path (RDKAFKA_INCLUDE_DIR NAMES librdkafka/rdkafka.h PATHS ${RDKAFKA_INCLUDE_PATHS})
    if (USE_STATIC_LIBRARIES AND NOT OS_FREEBSD)
       find_library (SASL2_LIBRARY sasl2)
    endif ()
endif ()
```

i think that part must be move below the line `if (RDKAFKA_LIB AND RDKAFKA_INCLUDE_DIR)`:
```
    if (USE_STATIC_LIBRARIES AND NOT OS_FREEBSD)
       find_library (SASL2_LIBRARY sasl2)
    endif ()
```

**Comment by mcarbonneaux** [comment] 2019-02-26 17:33
i think the problem is because you use your cmakelist... and hardcode librdkafka flag...

in https://github.com/yandex/ClickHouse/blob/master/contrib/librdkafka-cmake/config.h you commented sasl flag...

```
// #define ENABLE_SASL 1
// #define WITH_SASL_SCRAM 1
```

the good version vorking with sasl/scram with cmake are https://github.com/edenhill/librdkafka/commit/7691b20ff60f6158da8184014cfa80501df11707.

i think you need also `WITH_SASL_CYRUS`...

**Comment by filimonov** [comment] 2019-05-06 23:22
@mcarbonneaux  did you succeed with that?

**Comment by abyss7** [comment] 2019-05-13 11:58
Technically the duplicate of #2551

**Closed by abyss7** 2019-05-13 11:58 UTC
Labels: build, comp-kafka

**Comment by mcarbonneaux** [comment] 2019-05-14 13:09
I've started test but I've not the time to finalize and test for the moment.

But they must add all source related to sasl in cmakefile of rdkafka and add os sasl library in linking phase... 

The ideal must to add static sasl but is more complex change....

**Comment by mcarbonneaux** [comment] 2019-05-15 12:08
i've done quasi the same as https://github.com/yandex/ClickHouse/pull/5253.

```
diff --git a/cmake/find_rdkafka.cmake b/cmake/find_rdkafka.cmake
index de34f37..206aa21 100644
--- a/cmake/find_rdkafka.cmake
+++ b/cmake/find_rdkafka.cmake
@@ -15,14 +15,12 @@ endif ()
 if (NOT USE_INTERNAL_RDKAFKA_LIBRARY)
     find_library (RDKAFKA_LIB rdkafka)
     find_path (RDKAFKA_INCLUDE_DIR NAMES librdkafka/rdkafka.h PATHS ${RDKAFKA_INCLUDE_PATHS})
-    if (USE_STATIC_LIBRARIES AND NOT OS_FREEBSD)
-       find_library (SASL2_LIBRARY sasl2)
-    endif ()
 endif ()

 if (RDKAFKA_LIB AND RDKAFKA_INCLUDE_DIR)
     set (USE_RDKAFKA 1)
     set (RDKAFKA_LIBRARY ${RDKAFKA_LIB} ${OPENSSL_LIBRARIES})
+    find_library (SASL2_LIBRARY sasl2)
     if (SASL2_LIBRARY)
        list (APPEND RDKAFKA_LIBRARY ${SASL2_LIBRARY})
     endif ()
@@ -31,6 +29,10 @@ if (RDKAFKA_LIB AND RDKAFKA_INCLUDE_DIR)
     endif ()
 elseif (NOT MISSING_INTERNAL_RDKAFKA_LIBRARY AND NOT ARCH_ARM)
     set (USE_INTERNAL_RDKAFKA_LIBRARY 1)
+    find_library (SASL2_LIBRARY sasl2)
+    if (SASL2_LIBRARY)
+       list (APPEND RDKAFKA_LIBRARY ${SASL2_LIBRARY})
+    endif ()
     set (RDKAFKA_INCLUDE_DIR "${ClickHouse_SOURCE_DIR}/contrib/librdkafka/src")
     set (RDKAFKA_LIBRARY rdkafka)
     set (USE_RDKAFKA 1)
@@ -38,4 +40,4 @@ endif ()

 endif ()

-message (STATUS "Using librdkafka=${USE_RDKAFKA}: ${RDKAFKA_INCLUDE_DIR} : ${RDKAFKA_LIBRARY}")
+message (STATUS "Using librdkafka=${USE_RDKAFKA}: ${RDKAFKA_INCLUDE_DIR} : ${RDKAFKA_LIBRARY} : ${SASL2_LIBRARY}")
```

```
diff --git a/contrib/librdkafka-cmake/CMakeLists.txt b/contrib/librdkafka-cmake/CMakeLists.txt
index 90421cf..70f5243 100644
--- a/contrib/librdkafka-cmake/CMakeLists.txt
+++ b/contrib/librdkafka-cmake/CMakeLists.txt
@@ -52,9 +52,14 @@ ${RDKAFKA_SOURCE_DIR}/lz4.c
 ${RDKAFKA_SOURCE_DIR}/lz4frame.c
 ${RDKAFKA_SOURCE_DIR}/lz4hc.c
 ${RDKAFKA_SOURCE_DIR}/rdgz.c
+${RDKAFKA_SOURCE_DIR}/rddl.c
+${RDKAFKA_SOURCE_DIR}/rdkafka_plugin.c
+${RDKAFKA_SOURCE_DIR}/rdkafka_sasl_cyrus.c
+${RDKAFKA_SOURCE_DIR}/rdkafka_sasl_scram.c
 )

+
 add_library(rdkafka ${LINK_MODE} ${SRCS})
 target_include_directories(rdkafka PRIVATE include)
 target_include_directories(rdkafka SYSTEM PUBLIC ${RDKAFKA_SOURCE_DIR})
-target_link_libraries(rdkafka PUBLIC ${ZLIB_LIBRARIES} ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})
+target_link_libraries(rdkafka PUBLIC ${SASL2_LIBRARY} ${ZLIB_LIBRARIES} ${OPENSSL_SSL_LIBRARY} ${OPENSSL_CRYPTO_LIBRARY})
```

```
diff --git a/contrib/librdkafka-cmake/config.h b/contrib/librdkafka-cmake/config.h
index 68e93a1..cfbc980 100644
--- a/contrib/librdkafka-cmake/config.h
+++ b/contrib/librdkafka-cmake/config.h
@@ -10,7 +10,7 @@
 #define ENABLE_SHAREDPTR_DEBUG 0
 #define ENABLE_LZ4_EXT 1
 #define ENABLE_SSL 1
-//#define ENABLE_SASL 1
+#define ENABLE_SASL 1
 #define MKL_APP_NAME "librdkafka"
 #define MKL_APP_DESC_ONELINE "The Apache Kafka C/C++ library"
 // distro
@@ -46,9 +46,9 @@
 // parseversion
 #define MKL_APP_VERSION "0.11.4"
 // libdl
-//#define WITH_LIBDL 1
+#define WITH_LIBDL 1
 // WITH_PLUGINS
-//#define WITH_PLUGINS 1
+#define WITH_PLUGINS 1
 // zlib
 #define WITH_ZLIB 1
 // WITH_SNAPPY
@@ -58,7 +58,11 @@
 // libssl
 #define WITH_SSL 1
 // WITH_SASL_SCRAM
-//#define WITH_SASL_SCRAM 1
+#define WITH_SASL_SCRAM 1
+// WITH_SASL_CYRUS
+#define WITH_SASL_CYRUS 1
+// SOLIB_EXT ".so"
+#define SOLIB_EXT ".so"
 // crc32chw
 #define WITH_CRC32C_HW 1
 // regex
```

**Comment by filimonov** [comment] 2020-09-22 10:47
Related #12771 
/cc  @ilejn
