### ISSUE TITLE
Lots of 'DB::Exception: Unknown packet from client' in logs under extreme load tests

### ISSUE THREAD

**Issue by msoltyspl** [yandex/ClickHouse#1522] opened 2017-11-20 21:49 UTC
Hi,

We've put 6 clickhouse servers (2 replicas x 3 shards, under 6 zookepers in 5+1(observer) configuration) under some heavy artificial load - essentially we needed to test behaviour with ~year worth of data generated quickly, but we also were genuinely curious about "what would happen" as well. Each server is 2 x 10core x 2thread machine with 128GB ram. The versions are 1.1.54310 (official clickhouse debs) and 1.4.11 (zookeeper).

On each of those servers, 10 processes were spawned piping directly into 10 clickhouse clients, essentially:

    clickhouse-client -h 127.0.0.1 --query='INSERT INTO cdn.access_log FORMAT JSONEachRow' <&${DESCS_RIGHT[n]} &

Getting data from 10 "feeders" outputting to respective pipes, and one overseer script keeping an eye on the whole thing, restarting clickhouse-clients whether whenever they were kicked out (which was happening rather frequently, see below). All in all - 60 processes were attacking 6 clickhouse servers, 10 per server, each over localhost, with speed ~370k+ log lines per second per one generator.

Now to the logs, there were some expected messages (or at least I think they were expected, not sure if there are any tunables to workaround them - keep in mind that the load we have tested is roughly 1500x bigger than what we expect in production):

    2017.11.17 19:00:45.500481 [ 61 ] <Error> access_log.Distributed.DirectoryMonitor: Code: 252, e.displayText() = DB::Exception: Received from 10.230.238.25:9000. DB::Exception: Too many parts (302). Merges are processing significantly slower than inserts.. Stack trace:

Lots of informational debug stuff, such as:

    2017.11.17 20:12:22.320488 [ 16 ] <Debug> cdn.access_log_local (ReplicatedMergeTreeQueue): Not executing log entry for part 20170301_20170305_118_718_3 because its size (5.28 GiB) is greater than current maximum (4.45 MiB).

And some somewhat worrying ones, though it seems successfully handled overall:

    2017.11.17 19:45:41.567904 [ 26 ] <Warning> cdn.access_log_local (StorageReplicatedMergeTree): Part 20170127_20170127_4478_4478_0 from own log doesn't exist.
    2017.11.17 19:45:41.593215 [ 26 ] <Information> cdn.access_log_local (StorageReplicatedMergeTree): DB::Exception: No active replica has part 20170127_20170127_4478_4478_0 or covering part
    2017.11.17 19:45:41.604005 [ 66 ] <Warning> cdn.access_log_local (StorageReplicatedMergeTree, PartCheckThread): Checking part 20170127_20170127_4478_4478_0
    2017.11.17 19:45:41.607973 [ 66 ] <Warning> cdn.access_log_local (StorageReplicatedMergeTree, PartCheckThread): Checking data of part 20170127_20170127_4478_4478_0.
    2017.11.17 19:45:41.818394 [ 66 ] <Information> cdn.access_log_local (StorageReplicatedMergeTree, PartCheckThread): Part 20170127_20170127_4478_4478_0 looks good.
    2017.11.17 19:45:43.637724 [ 33 ] <Debug> cdn.access_log_local (Merger): Merging 6 parts: from 20170126_20170126_4473_4473_0 to 20170127_20170127_4478_4478_0 into tmp_merge_20170125_20170128_4473_4478_

But there were also less expected ones such as (here along with the stack trace):

    2017.11.17 19:15:01.373381 [ 50 ] <Error> ServerErrorHandler: Code: 99, e.displayText() = DB::Exception: Unknown packet from client, e.what() = DB::Exception, Stack trace:
    
    0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x3419e66]
    1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x1f) [0x14f2a9f]
    2. /usr/bin/clickhouse-server(DB::TCPHandler::receivePacket()+0x21f) [0x14fe21f]
    3. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x55c) [0x14ff92c]
    4. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x150055b]
    5. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x3ae7c5f]
    6. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xad) [0x3aecead]
    7. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x86) [0x3a1bad6]
    8. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x39facf8]
    9. /usr/bin/clickhouse-server() [0x4290b0f]
    10. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fae8590b6ba]
    11. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fae84f2c3dd]

This matched the logs on the log generator side:

    Nov 17 19:15:03 cdn-a-2-24 logmachine.sh[24597]: Code: 210. DB::NetException: Connection reset by peer while writing to socket (127.0.0.1:9000)
    Nov 17 19:15:07 cdn-a-2-24 logmachine.sh[24597]: Clickhouse client #0 GONE, detected at Fri, 17 Nov 2017 19:15:07 +0100, restarting

This was happening on every server and with every client - and usually quite frequently. On the machine above (a-2-24) this was particularly frequent - every 12 seconds or so. Which makes wonder if we triggered some obscure bug this way (and whether it's the client or the server that was at fault), or if it's just clickhouse-server way of saying "slow down" to the clients. On some machines it didn't happen that often (every 1-2 minutes), on one of them it even stopped altogether after few initial connection resets.

All in all we managed to insert ~220b (of 240b that should go in, so notable loss - dunno if only due to clients getting kicked regularly or something else as well) logs in mere 3 hours, though it took ~10 more hours (basing on log activity) to tidy up everything on each server by the clickhouse-servers process.

On zookeper sides, everything seemed clean besides tons of INFO and lower messages, such as:

    2017-11-17 21:28:57,939 [myid:5] - INFO  [ProcessThread(sid:5 cport:-1)::PrepRequestProcessor@653] - Got user-level KeeperException when processing sessionid:0x600a6f95f140000 type:delete cxid:0x5a25b1fd zxid:0x1002203f8 txntype:-1 reqpath:n/a Error Path:/clickhouse/tables/3/access_log_local/temp/abandonable_lock-0000078695 Error:KeeperErrorCode = NoNode for /clickhouse/tables/3/access_log_local/temp/abandonable_lock-0000078695
    
    2017-11-17 20:18:00,467 [myid:5] - INFO  [ProcessThread(sid:5 cport:-1)::PrepRequestProcessor@596] - Got user-level KeeperException when processing sessionid:0x10112677b250000 type:multi cxid:0x5a18308c zxid:0x100127e0c txntype:-1 reqpath:n/a aborting remaining multi ops. Error Path:/clickhouse/tables/3/access_log_local/blocks/11127397126160108611_13169767591795659356 Error:KeeperErrorCode = NodeExists for /clickhouse/tables/3/access_log_local/blocks/11127397126160108611_13169767591795659356

Either way, the aforementioned 'unknown packet' exceptions from standard clickhouse-clients do look like a bug.

**Comment by perez1987** [comment] 2018-02-26 14:04
Any news? I have same issue

**Comment by YindSoft** [comment] 2018-05-15 17:30
so do I

**Comment by sleshJdev** [comment] 2018-10-09 12:09
I am experienced the exactly same issue, but in my case I don't have much less load: I pull files from s3 bucket one by one and pipe them to clickhouse thru clickhouse-client. And sometimes I don't now why I see discrepancy of data that seems like some of files was not imported correctly. The only errors I found in server logs are the same error as TC described above. Any idea how to fix this?  Thanks in advance!

**Comment by doom369** [comment] 2019-08-14 17:08
Getting the same error:

```
2019.08.14 16:31:16.739119 [ 43 ] {} <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace:

0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x30) [0x7f58f30]
1. /usr/bin/clickhouse-server(DB::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x25) [0x3c427b5]
2. /usr/bin/clickhouse-server() [0x37b9d98]
3. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x1f4) [0x3c83704]
4. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x3c847cb]
5. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0x10) [0x792cde0]
6. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xed) [0x792d4fd]
7. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x8057e21]
8. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x3c) [0x8055bcc]
9. /usr/bin/clickhouse-server() [0xba2baa0]
10. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f33f58bb6db]
11. /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f33f504288f]
 (version 19.13.1.11 (official build))
```

Found in regular log this:

```
2019.08.14 16:31:16.685354 [ 43 ] {} <Trace> TCPHandlerFactory: TCP Request. Address: [::ffff:92.14.104.106]:50203
2019.08.14 16:31:16.739119 [ 43 ] {} <Error> ServerErrorHandler: Code: 101, e.displayText() = DB::NetException: Unexpected packet from client, Stack trace:
```

Look like it could be some kind of scanner that crawls all ports. As this is not our IP.
I'll do binding to the local network IP in order to make sure this is scanners.

**Comment by seanlook** [comment] 2019-08-27 15:10
Got the same error in distributed table:
```
0. clickhouse-server(StackTrace::StackTrace()+0x16) [0x65cbc16]
1. clickhouse-server(DB::RemoteBlockOutputStream::RemoteBlockOutputStream(DB::Connection&, std::string const&, DB::Settings const*)+0xa13) [0x60a50c3]
2. clickhouse-server(DB::StorageDistributedDirectoryMonitor::processFile(std::string const&)+0xcb) [0x5e0f25b]
3. clickhouse-server(DB::StorageDistributedDirectoryMonitor::findFiles()+0x125) [0x5e108d5]
4. clickhouse-server(DB::StorageDistributedDirectoryMonitor::run()+0x66) [0x5e10dd6]
5. clickhouse-server(_ZZN20ThreadFromGlobalPoolC4IMN2DB34StorageDistributedDirectoryMonitorEFvvEJPS2_EEEOT_DpOT0_ENKUlvE_clEv+0x35) [0x5e12095]
6. clickhouse-server(ThreadPoolImpl<std::thread>::worker(std::_List_iterator<std::thread>)+0x1b8) [0x65d4bf8]
7. clickhouse-server() [0x711163f]
8. /lib64/libpthread.so.0(+0x79d1) [0x7f0c0f1849d1]
9. /lib64/libc.so.6(clone+0x6d) [0x7f0c0e3258ed]
 (version 19.9.5.36)
```

**Comment by alexey-milovidov** [comment] 2019-09-02 18:59
https://github.com/yandex/ClickHouse/issues/5891

**Comment by alexey-milovidov** [comment] 2019-09-07 17:12
It should be fixed in master and in 19.14 (prestable).

**Closed by alexey-milovidov** 2019-09-07 17:12 UTC

**Comment by azat** [comment] 2021-09-11 21:26
Yes, right now it is still possible to get these messages after query cancelations/connection close.

**Comment by yangmeng66** [comment] 2021-09-12 01:45
Hello @azat, I'm very sorry, I didn't understand what you mean. I am not the same as the situation above. I used clickhouse's third-party JDBC driver (ClickHouse-Native-JDBC) to report an error when importing data. You Do you know the reason?


![image](https://user-images.githubusercontent.com/51857567/132967928-b546a03a-1f13-4985-ba76-80a69c9cb920.png)

**Comment by alexey-milovidov** [comment] 2021-09-12 02:03
ClickHouse-Native-JDBC is unsupported, migrate to ClickHouse-JDBC.

**Comment by lyj2871** [comment] 2021-10-20 01:56
This problem may be caused by multi-threaded operations. The write operation in one thread has not yet been completed, and another thread initiates a read and write operation.
