### ISSUE TITLE
Query wrong result 18.14.8(9) (CH cashes ? subquery result)

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#3410] opened 2018-10-17 19:21 UTC
Preparing:

CREATE TABLE dt(tkey Int32) ENGINE = MergeTree order by tuple();
insert into dt values (300000);
CREATE TABLE testx(t Int32, a UInt8) ENGINE = MergeTree ORDER BY tuple();
INSERT INTO testx VALUES (100000, 0);
**select count(*) from testx  where not a and t < (select tkey from dt);** 
1
drop table dt;
CREATE TABLE dt(tkey Int32) ENGINE = MergeTree order by tuple();
insert into dt values (0);

BUG:
**select count(*) from dw.testx  where not a and t < (select tkey from dt);**
**1**
select tkey from dt
0
select count(*) from dw.testx  where not a and t < 0
0

So CH does not see that value in the table dt has changed from 300000 to 0.

optimize_move_to_prewhere	0	
enable_optimize_predicate_expression	0

**Comment by den-crane** [comment] 2018-10-18 02:53
Workarond: move all other conditions to prewhere and leave the only the condition with subquery in where section.

select count(*) from testx 
prewhere not a  
where  t < (select tkey from dt);

**Comment by den-crane** [comment] 2018-10-19 18:01
select count(*) from dw.testx where not a and t < (select tkey from dt);
┌─count()─┐
│       1 │
└─────────┘
1 rows in set. Elapsed: 0.002 sec.

 **set compile_expressions  = 0;**

select count(*) from dw.testx where not a and t < (select tkey from dt);
0 rows in set. Elapsed: 0.002 sec.

**Comment by den-crane** [comment] 2018-10-19 18:12
In our system we don't drop/create dt.
It's a replacingmergetree table and it's data is different for every query.
And more complicated 
_time_key < (select time_key from dim_time where time_stamp = (select max(last_record_time) from data_status_current))_
dim_time is constant, data_status_current has different max data every time.

**Comment by alesapin** [comment] 2018-10-19 19:40
Den, I can't reproduce the problem from your example:
My steps:
```
:) CREATE TABLE dt(tkey Int32) ENGINE = MergeTree order by tuple();

Ok.

0 rows in set. Elapsed: 0.002 sec. 
:)  insert into dt values (300000);

Ok.

1 rows in set. Elapsed: 0.002 sec.
:)  CREATE TABLE testx(t Int32, a UInt8) ENGINE = MergeTree ORDER BY tuple();

Ok.

0 rows in set. Elapsed: 0.002 sec. 
:)  INSERT INTO testx VALUES (100000, 0);

Ok.

1 rows in set. Elapsed: 0.002 sec.
:)  select count(*) from testx where not a and t < (select tkey from dt);

┌─count()─┐
│       1 │
└─────────┘

1 rows in set. Elapsed: 0.004 sec. 

:) drop table dt;

Ok.

0 rows in set. Elapsed: 0.001 sec. 

:)  CREATE TABLE dt(tkey Int32) ENGINE = MergeTree order by tuple();

Ok.

0 rows in set. Elapsed: 0.003 sec.

:)  insert into dt values (0);

Ok.

1 rows in set. Elapsed: 0.002 sec. 
:)  select count(*) from testx where not a and t < (select tkey from dt);

┌─count()─┐
│       0 │
└─────────┘

1 rows in set. Elapsed: 0.004 sec. 
```
In last select query you use `dw.testx` table instead of `testx`, maybe this is the cause of wrong answer?

About expressions compilation:
1) Expressions are compiled when 3 identical expressions occur in queries. If you queried your select less then three times, then it's not compile expressions problem.
2) There is special asynchronous_metric in table `system.asynchronous_metrics` called `CompiledExpressionCacheCount`. Even after three times I called this expression metric doesn't increment. It means that this expression is too simple to be compiled. 

Maybe you can provide more complex example?

**Comment by den-crane** [comment] 2018-10-19 19:53
select name, value from system.settings where changed;

┌─name──────────────────────────────────────┬─value────────────┐
│ connect_timeout_with_failover_ms          │ 1000             │
│ use_uncompressed_cache                    │ 1                │
**│ optimize_move_to_prewhere                 │ 0**                │
│ load_balancing                            │ nearest_hostname │
│ compile_expressions                       │ 0                │
│ distributed_aggregation_memory_efficient  │ 1                │
│ skip_unavailable_shards                   │ 1                │
│ http_connection_timeout                   │ 15               │
**│ empty_result_for_aggregation_by_empty_set │ 1**                │
│ max_bytes_before_external_group_by        │ 25374640128      │
│ max_memory_usage                          │ 50749280256      │
└───────────────────────────────────────────┴──────────────────┘

**Comment by den-crane** [comment] 2018-10-19 19:55
it's tricky and works with engine = memory and sometimes caches other value

<img width="720" alt="screen shot 2018-10-19 at 4 50 28 pm" src="https://user-images.githubusercontent.com/19737682/47240740-babd9100-d3bf-11e8-880a-64adb5e4655f.png">

**Comment by alesapin** [comment] 2018-10-19 19:56
Can you provide `select * from system.asynchronous_metrics` ?

**Comment by den-crane** [comment] 2018-10-19 19:56
![screen shot 2018-10-19 at 2 53 12 pm](https://user-images.githubusercontent.com/19737682/47240820-e3de2180-d3bf-11e8-9ec9-4b2c3decd72a.png)

**Comment by den-crane** [comment] 2018-10-19 19:57
```
SELECT *
FROM system.asynchronous_metrics

┌─metric──────────────────────────────────┬──────value─┐
│ jemalloc.background_thread.run_interval │          0 │
│ jemalloc.background_thread.num_runs     │          0 │
│ jemalloc.background_thread.num_threads  │          0 │
│ jemalloc.retained                       │  557051904 │
│ jemalloc.mapped                         │ 2941521920 │
│ jemalloc.resident                       │ 2835759104 │
│ jemalloc.metadata_thp                   │          0 │
│ jemalloc.metadata                       │   15238536 │
│ jemalloc.allocated                      │ 2706048264 │
│ UncompressedCacheCells                  │        110 │
│ MarkCacheFiles                          │        110 │
│ ReplicasSumInsertsInQueue               │          0 │
│ MarkCacheBytes                          │       1760 │
│ UncompressedCacheBytes                  │    1420133 │
│ CompiledExpressionCacheCount            │          4 │
│ Uptime                                  │        723 │
│ ReplicasMaxQueueSize                    │          0 │
│ ReplicasMaxInsertsInQueue               │          0 │
│ ReplicasMaxMergesInQueue                │          0 │
│ ReplicasMaxRelativeDelay                │          0 │
│ jemalloc.active                         │ 2719969280 │
│ CompiledExpressionCacheBytes            │       4560 │
│ ReplicasSumQueueSize                    │          0 │
│ ReplicasMaxAbsoluteDelay                │          0 │
│ ReplicasSumMergesInQueue                │          0 │
│ MaxPartCountForPartition                │         10 │
└─────────────────────────────────────────┴────────────┘
```

**Comment by alesapin** [comment] 2018-10-19 20:00
yes, reproduced with:
```
optimize_move_to_prewhere 0
enable_optimize_predicate_expression 0
```

**Comment by den-crane** [comment] 2018-10-19 20:03
yes, I think optimize_move_to_prewhere 1
transform it to 
select count(*) from testx prewhere t <(subquery) where not a

**Comment by alesapin** [comment] 2018-10-19 20:07
Yes. This problem seems to be very special case. Сondition `t <(subquery) ` executes only when subquery returns single element.

**Comment by alesapin** [comment] 2018-10-19 21:05
https://github.com/yandex/ClickHouse/pull/3430/files hotfix

**Comment by den-crane** [comment] 2018-10-23 00:00
t.me/clickhouse_ru/71285

**Comment by alesapin** [comment] 2018-10-24 08:52
We disable compile expressions by default in 14.10.

**Comment by alesapin** [comment] 2018-10-26 16:02
Seems to be fixed in master https://github.com/yandex/ClickHouse/pull/3457. But we will test this feature more carefully.

**Closed** 2018-10-29 08:51 UTC
Labels: bug, issue
