### ISSUE TITLE
Feature: a keyword that saves the query's result to a file

### ISSUE THREAD

**Issue by hatarist** [yandex/ClickHouse#201] opened 2016-11-24 10:59 UTC
I think it'd be convenient to have this kind of feature in clickhouse-client.

MySQL has `INTO OUTFILE` syntax:

    SELECT * FROM hits INTO OUTFILE '/tmp/hits.tsv';

PostgreSQL has `COPY TO`:

    COPY (SELECT * FROM hits) TO '/tmp/hits.tsv';

It's a bit more plausible than having to copy the query to a file and running `cat query.sql | clickhouse-client`.

I suppose MySQL-like syntax will suit ClickHouse more:

    SELECT * FROM hits WHERE EventDate = '2016-11-24' LIMIT 100 FORMAT CSV OUTFILE '/tmp/hits.csv';

What do you think?

**Comment by alexey-milovidov** [comment] 2016-11-25 19:27
Duplicate of https://github.com/yandex/ClickHouse/issues/63
Now it is assigned.

**Closed** 2016-11-26 07:49 UTC
