### ISSUE TITLE
ODBC bridge with PostgreSQL requires prepared statements support

### ISSUE THREAD

**Issue by tarabanton** [yandex/ClickHouse#5376] opened 2019-05-22 07:13 UTC
Good day.
We are using external dictionaries in PostgreSQL via ODBC
There is two types of connections in our infrastructure:
- direct connection to Postgres
- connection via pooler (pgBouncer) in transaction mode

Database startup, when connecting via pooler fails.
`/etc/odbc.ini` contains `UseServerSidePrepare=No` for both types
It worked in 1.1.54370 (pre-odbc-bridge version)

**How to reproduce**
* Which ClickHouse server version to use
18.14.19
External dictionary via ODBC
External database: postgres
Use connection pooler between odbc and postgres. 
Connections Pooler: pgbouncer, but also tested with yandex\odyssey with same result
Pooling strategy: transaction

**Expected behavior**
Successful database startup in both cases

**Error message and/or stacktrace**
```
2019.05.22 07:01:43.222254 [ 1 ] {} <Error> Application: DB::Exception: Cannot create table from metadata file /var/lib/clickhouse/metadata/db//dict.sql, error: DB::Exception: Received error from remote server /?connection_string=DSN%3postgres_pgbouncer&columns=...&max_block_size=8192. HTTP status code: 500 Internal Server Error, body: �Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = ODBC handle exception: Failed to get number of columns: Connection:Not applicable
Server:postgres_pgbouncer
===========================
ODBC Diagnostic record #1:
===========================
SQLSTATE = 26000
Native Error Code = 1
ERROR: unnamed prepared statement does not exist;
No query has been executed with that handle

, e.what() = ODBC handle exception, stack trace:
0. /usr/bin/clickhouse-server(StackTrace::StackTrace()+0x16) [0x99d31a6]
1. /usr/bin/clickhouse-server(DB::receiveResponse(Poco::Net::HTTPClientSession&, Poco::Net::HTTPRequest const&, Poco::Net::HTTPResponse&)+0x191) [0x99ec2c1]
2. /usr/bin/clickhouse-server(DB::ReadWriteBufferFromHTTP::ReadWriteBufferFromHTTP(Poco::URI, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void (std::ostream&)>, DB::ConnectionTimeouts const&, Poco::Net::HTTPBasicCredentials const&, unsigned long)+0x2df) [0x9a0500f]
3. /usr/bin/clickhouse-server() [0x7c3557f]
4. /usr/bin/clickhouse-server(DB::XDBCDictionarySource::loadBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const+0x287) [0x7c365d7]
5. /usr/bin/clickhouse-server(DB::XDBCDictionarySource::loadAll()+0x107) [0x7c368d7]
6. /usr/bin/clickhouse-server(DB::FlatDictionary::loadData()+0x4e) [0x73e86ce]
7. /usr/bin/clickhouse-server(DB::FlatDictionary::FlatDictionary(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::DictionaryStructure const&, std::unique_ptr<DB::IDictionarySource, std::default_delete<DB::IDictionarySource> >, DB::ExternalLoadableLifetime, bool, std::shared_ptr<DB::Block>)+0x5da) [0x73e8e9a]
8. /usr/bin/clickhouse-server(DB::DictionaryFactory::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&) const+0x1310) [0x7ad9140]
9. /usr/bin/clickhouse-server(DB::ExternalDictionaries::create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Poco::Util::AbstractConfiguration const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x43) [0x7590913]
10. /usr/bin/clickhouse-server(DB::ExternalLoader::reloadFromConfigFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x12fb) [0x759400b]
11. /usr/bin/clickhouse-server(DB::ExternalLoader::reloadFromConfigFiles(bool, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xbb) [0x75965cb]
12. /usr/bin/clickhouse-server(DB::ExternalLoader::reloadAndUpdate(bool)+0x61) [0x7596ca1]
13. /usr/bin/clickhouse-server(DB::ExternalLoader::init(bool)+0x65) [0x7598395]
14. /usr/bin/clickhouse-server(DB::ExternalDictionaries::ExternalDictionaries(std::unique_ptr<DB::IExternalLoaderConfigRepository, std::default_delete<DB::IExternalLoaderConfigRepository> >, DB::Context&, bool)+0x1d0) [0x7591010]
15. /usr/bin/clickhouse-server(DB::Context::getExternalDictionariesImpl(bool) const+0xf0) [0x7543e30]
16. /usr/bin/clickhouse-server() [0x7ba4eda]
17. /usr/bin/clickhouse-server(DB::StorageFactory::get(DB::ASTCreateQuery&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, DB::Context&, DB::ColumnsDescription const&, bool, bool) const+0x1fe) [0x773491e]
18. /usr/bin/clickhouse-server(DB::createTableFromDefinition(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, DB::Context&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x10a) [0x6b7071a]
19. /usr/bin/clickhouse-server() [0x79faf26]
20. /usr/bin/clickhouse-server() [0x79fb5f4]
21. /usr/bin/clickhouse-server(ThreadPool::worker()+0x19e) [0x9bd63ce]
22. /usr/bin/clickhouse-server() [0xa3c68cf]
23. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7f241efd46ba]
24. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f241e5f541d]

2019.05.22 07:01:43.222307 [ 1 ] {} <Information> Application: shutting down
2019.05.22 07:01:43.222313 [ 1 ] {} <Debug> Application: Uninitializing subsystem: Logging Subsystem
2019.05.22 07:01:43.222333 [ 2 ] {} <Information> BaseDaemon: Stop SignalListener thread
```

**Comment by akuzm** [comment] 2019-05-27 11:03
This looks like some race condition when using extended query protocol in postgres, e.g. a Bind message arrives before Parse message. I'd expect UseServerSidePrepare=0 to disable extended protocol, but apparently it's still used. Will try to reproduce.

**Comment by tarabanton** [comment] 2019-05-27 11:10
> This looks like some race condition when using extended query protocol in postgres, e.g. a Bind message arrives before Parse message. I'd expect UseServerSidePrepare=0 to disable extended protocol, but apparently it's still used. Will try to reproduce.

FYI: In single-node setup bug is hard to reproduce. When we tested new version on single node setup, bug was unnoticed. 
Only when we set it up on three-node cluster, we noticed it on the start of second node. As long as there is more than one node - it can be reproduced in almost 100% of cases.

**Comment by akuzm** [comment] 2019-06-27 14:52
After reading more about this, it seems that pgbouncer does not support prepared statements in transaction pooling mode, so the error is expected.
I tried installing psqlodbc and configuring a simple data source:
```
# cat /etc/odbc.ini 
[postgres]
Driver = /usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
Servername = 127.0.0.1
Port = 5432
Username = akuzm
Database = postgres
UseServerSidePrepare = 1
```

In postgres config, I set `log_statement = 'all'` and `log_min_duration_statement = 0`, so that extended protocol messages Parse, Bind etc. are logged as well. I run `isql -v postgres` to test the connection, execute `select 1;` and see in the postgres log:
```
2019-06-27 17:44:58.580 MSK [15929] LOG:  duration: 0.153 ms  parse _PLAN0x56401a402920: select 1
2019-06-27 17:44:58.581 MSK [15929] LOG:  duration: 0.083 ms  bind _PLAN0x56401a402920: select 1
2019-06-27 17:44:58.581 MSK [15929] LOG:  execute _PLAN0x56401a402920: select 1
```
This means that the odbc driver is using extended query protocol.

After that, I set `UseServerSidePrepare = 0`, do the same thing, and the postgres log says:
```
2019-06-27 17:47:34.567 MSK [15966] LOG:  statement: select 1;
2019-06-27 17:47:34.568 MSK [15966] LOG:  duration: 0.424 ms
```
This means that simple query protocol is used. So `UseServerSidePrepare` works in my setup.
I'm on Ubuntu 18.04.2, the packages are:
```
# aptitude search odbc -F "%c %p %d %V" | grep ^i
i libodbc1 ODBC library for Unix 2.3.4-1.1ubuntu3
i odbc-postgresql ODBC driver for PostgreSQL 1:10.01.0000-1
i odbcinst Helper program for accessing odbc ini files 2.3.4-1.1ubuntu3
i odbcinst1debian2 Support library for accessing odbc ini files 2.3.4-1.1ubuntu3
i unixodbc Basic ODBC tools 2.3.4-1.1ubuntu3
```
Postgres is compiled from current master. 

Anyway, this seems to be an issue of ODBC configuration not specific to Clickhouse.

**Comment by tarabanton** [comment] 2019-07-15 14:21
Of course we know about it. That's why we set `UseServerSidePrepare = 0`

**Comment by akuzm** [comment] 2019-07-15 18:10
Could you run a query against your ODBC source with isql or some other client, and look at the postgres logs to confirm that it doesn't use prepared statements? That way we can make sure that the ODBC source is configured correctly.

**Comment by akuzm** [comment] 2019-08-30 12:45
I will close this for now, feel free to reopen if there are any news.

**Closed by akuzm** 2019-08-30 12:45 UTC
Labels: bug, comp-foreign-db
