### ISSUE TITLE
Something wrong with versioning

### ISSUE THREAD

**Issue by kvap** [yandex/ClickHouse#2792] opened 2018-08-02 11:29 UTC
I tried a docker image of ClickHouse, and it gives some strange version strings.

I start the server like this:
```
docker run --rm -p 9001:9000 -d --name testch --ulimit nofile=262144:262144 yandex/clickhouse-server:18.1.0
```

And then connect to it with the client and execute this:
```
0e2112272841 :) select version(123)

SELECT version(123)

Received exception from server (version 18.4.54399):
Code: 42. DB::Exception: Received from localhost:9001, 127.0.0.1. DB::Exception: Number of arguments for function version doesn't match: passed 1, should be 0. 

0 rows in set. Elapsed: 0.182 sec. 

0e2112272841 :) select version()

SELECT version()

┌─version()─┐
│ 18.4.0    │
└───────────┘

1 rows in set. Elapsed: 0.003 sec. 

0e2112272841 :) Bye.
```

Notice how in one case it is `18.4.54399`, in another `18.4.0`, and the image is supposed to be `18.1.0`.

**Comment by alesapin** [comment] 2018-08-02 12:09
Currently ClickHouse has problems caused by new versioning. They will be fixed with new releases, some of them are fixed inside [this commit](https://github.com/yandex/ClickHouse/commit/d72ba2701b90541f916d5e030e42617b09d5c6d7).

**Comment by alesapin** [comment] 2018-08-03 09:16
Also, you got 18.4 instead 18.1 inside docker image because of accidental error in release cycle. This issue applies only to the 18.1 image.

**Closed by alesapin** 2018-08-03 09:16 UTC
