### ISSUE TITLE
getrandom call from HDFS brake compatibility with older kernels & glibc

### ISSUE THREAD

**Issue by lordk911** [yandex/ClickHouse#5974] opened 2019-07-11 11:27 UTC
I've tried to create a table with engine HDFS to read Parquet type file, When I try to select * from the table ,I got error :

Received exception from server (version 19.9.2):
Code: 210. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Unable to connect to HDFS: getrandom.

**Comment by lordk911** [comment] 2019-07-12 05:24
logs from error.log :

2019-07-11 19:08:43.884803, p26368, th140517123806976, ERROR Unexpected exception N5boost10wrapexceptINS_5uuids13entropy_errorEEE: getrandom
2019-07-11 19:25:18.846773, p26368, th140517123806976, ERROR Unexpected exception N5boost10wrapexceptINS_5uuids13entropy_errorEEE: getrandom

**Comment by lordk911** [comment] 2019-07-12 05:38
uname -r
3.10.0-514.el7.x86_64   
should be 3.17+ ?

**Comment by lordk911** [comment] 2019-07-12 10:44
after update linux kernel to 5.2.0 , I can read parquet from HDFS.

**Comment by filimonov** [comment] 2019-07-15 11:12
Rather should be fixed other way, as we prefer to have compatibility with older kernel & glibc.

Do you have full stacktraces of error? Usually can be found near exception in log.

**Comment by filimonov** [comment] 2019-09-09 21:37
Actually it's a duplicate of https://github.com/yandex/ClickHouse/issues/4197 (which have full stacktraces), so let's continue there.

**Closed by filimonov** 2019-09-09 21:37 UTC
Labels: bug, build
