### ISSUE TITLE
how do we check when Clickhouse finishes all merge operations?

### ISSUE THREAD

**Issue by q0987** [yandex/ClickHouse#3868] opened 2018-12-18 22:31 UTC
```
:) select * from system.merges

SELECT *
FROM system.merges
Ok.
0 rows in set. Elapsed: 0.002 sec.
```
Based on my understanding, the Clickhouse will start to merge the data after it has been loaded into the DB. When querying directly on unmerge data, the query performance is not optimized.

Question> How do we know the Clickhouse finishes all pending merge operations?
Is it true that we can check this through the system.merges? If the table is empty, then we can assume that the merging operations are done?

Thank you

**Comment by den-crane** [comment] 2018-12-18 23:47
>Based on my understanding, ...
it's not quite right. There is a merge scheduler which plans merges for a table to reduce number of parts without causing I/O starvation. All merges will be finished eventually = never.

You should not bother about unmerged data. 99.99% performance cases related to other issues such as wrong partitioning / where clauses / sort-key misdesign.

>Is it true that we can check this through the system.merges?  
No. system.merges reflects running merges. Merge could be scheduled to run in some future.

select count() parts_count, database,table,partition  from system.parts 
where   table like '%your_table%' and active  group by database,table,partition
order by parts_count desc

you can check parts_count , if it's >1 then it's still can be merged.
And it's also is not quite right because parts of the table can reach max size and will not be merged anymore.

**Closed** 2018-12-24 11:19 UTC

**Comment by yaroslavzinchenko** [comment] 2021-07-24 10:33
@den-crane Is there a way to force scheduled parts to merge? I have a lot of parts in `system.parts` table and I want to merge them.

**Comment by sanket-winzo** [comment] 2023-05-22 13:40
Is there any way to manually start merge operation? Since there are plenty of unmerged files and it is causing issues

```
Code: 252. DB::Exception: Too many parts (800 with average size of 71.34 MiB) in table table_name. Merges are processing significantly slower than inserts. (TOO_MANY_PARTS) 
```

**Comment by fillest** [comment] 2023-09-01 15:08
@yaroslavzinchenko @sanket-winzo you most likely need to _prevent_ generating too much parts, not to constantly deal with consequences. Usually the problem is that you make too frequent small inserts - you need to batch them into less frequent bigger inserts - either manually or using "asynchronous inserts" feature

**Comment by sanket-winzo** [comment] 2023-09-11 13:51
We were doing all that. Batch inserting at intervals. 2/3 nodes were merging files and running smoothly, but 1 of the nodes were not able to merge files. We even stopped inserting data for 5 days all together and still number of files didn't decrease.

**Comment by fillest** [comment] 2023-09-11 17:14
> We were doing all that. Batch inserting at intervals. 2/3 nodes were merging files and running smoothly, but 1 of the nodes were not able to merge files. We even stopped inserting data for 5 days all together and still number of files didn't decrease.

If the nodes have the same software, hardware and load, at that point I would suspect either a hardware problem or maybe if you are running a raid on HDDs, a scrubbing could be triggered - it can destroy performance in some cases. Compare monitoring graphs for the nodes, /proc/mdstat, smartctl and so on
