### ISSUE TITLE
WHERE statement using IN operand for list with one element

### ISSUE THREAD

**Issue by goranc** [yandex/ClickHouse#313] opened 2017-01-10 14:07 UTC
There is change in operations with IN operand used in WHERE statement In ClickHouse server version 1.1.54127.
When we use statement ... WHERE column IN ('specified_value')
we get error  DB::Exception: Not found column 'specified_value' in block.

If we specify WHERE column IN ('specified_value','') -- with two entries in list
then it works, or if we use equal sign instead of IN operand.

In previous version of the server it was working with single element in list.

g.c.

**Comment by artpaul** [comment] 2017-01-10 16:32
I think it has been fixed in master.

**Comment by hatarist** [comment] 2017-01-11 07:56
I can confirm that `WHERE ... IN ...` statement is broken, but in my case the problem seems to be weirder:

```
-- `table` has a MergeTree engine
CREATE TABLE table_buffer AS table;

-- some data was inserted to `table_buffer`

-- trying to insert the data from the `table_buffer` to the `table` with a filter that prevents dupes
INSERT INTO table SELECT DISTINCT
    id, date, timestamp, field1, field2, field3, field4, field5, now() AS created_at
FROM table_buffer
WHERE (id, date) NOT IN (
    SELECT DISTINCT id, date FROM table WHERE timestamp >= '2017-01-10 11:46:35' AND timestamp <= '2017-01-11 03:40:09'
);

Code: 16, e.displayText() = DB::Exception: There is no column with name field3. There are columns: id, created_at, date, timestamp, field1, field2, field3, field4, field5, field6, field7, e.what() = DB::Exception
```

(actual field list is a bit different).

We have this kind of problem right after updating from the 1.1.54083 with two separate MergeTree tables (~200M rows each). The problematic fields are of the `UInt32` type, not sure if it is relevant or just a coincidence.

**Comment by bozerkins** [comment] 2017-01-12 12:08
what was the reason for merging the #314 ?

the error now is more than misleading. 
the _dummy column isn't mentioned anywhere in documentation.

**Comment by artpaul** [comment] 2017-01-12 12:16
>>> the _dummy column isn't mentioned anywhere in documentation.
This is internal constant. You can find it in the same file.

>>> the error now is more than misleading.
Do you have any example of same error which was not fixed?

**Comment by bozerkins** [comment] 2017-01-13 01:16
i was a release behind. it seems to be working fine now.

sorry for disturbing

**Closed** 2017-02-08 10:51 UTC
