### ISSUE TITLE
Couldn't parse csv file if value contains from '

### ISSUE THREAD

**Issue by sleshJdev** [yandex/ClickHouse#2517] opened 2018-06-15 13:04 UTC
Hi, guys!

Here is demo DDL:

```
CREATE TABLE X (
    eventdate        Date default toDate(now()),
    f1               String,
    f2               String,
    f3	             String
) ENGINE = MergeTree(eventdate, (f1, f2, f3), 8192)
```

When I try to import data, clickhous fails with error:

```
$echo "US,'Ewa Beach, Test" | clickhouse-client --database default --query "insert into X(f1, f2, f3) format CSV"

Code: 27. DB::Exception: Cannot parse input: expected , at end of stream.: (at row 1)
```

```
$ clickhouse-client --version
ClickHouse client version 1.1.54385.
```

The problem is **'** symbol in the value of field _f2_.
**Please, any workaround to make it works?**

Interesting that if left only two fields, it parses csv correctly.

```
CREATE TABLE X (
    eventdate        Date default toDate(now()),
    f1               String,
    f2               String
) ENGINE = MergeTree(eventdate, (f1, f2), 8192)

$echo "US,'Ewa Beach" | clickhouse-client --database default --query "insert into X(f1, f2) format CSV"
```

**Comment by sleshJdev** [comment] 2018-06-15 13:36
Maybe is there some option to force using a only double quote as a string delimiter, and consider single quote as plain symbol without special meaning? Please, any solution is welcome.

**Comment by sleshJdev** [comment] 2018-06-15 13:38
I just tested with same values but as _tsv_, and it works. But unfortunately I cannot migrate to _tsv_ right now. I need to find out some workaround for _csv_ to make it work with signle quote in field value.

**Comment by sleshJdev** [comment] 2018-06-15 13:44
I asked the [question](https://stackoverflow.com/questions/50876839/couldnt-parse-csv-file-if-value-start-from-or) on the SO also.

**Comment by KochetovNicolai** [comment] 2018-06-18 09:54
Now there is no option to use only double quote. It seems that the best way is to prepare data before insertion. For example, wrap `'Ewa Beach` into double quotes.

**Comment by filimonov** [comment] 2018-06-20 04:11
Duplicate of #2192

Important notice - because of that clickhouse csv parser is not RFC compatible.

**Closed** 2018-07-19 18:17 UTC
