### ISSUE TITLE
Delete some rows failed

### ISSUE THREAD

**Issue by smallfish** [yandex/ClickHouse#3086] opened 2018-09-10 04:09 UTC
Delete some rows like:

```
ALTER TABLE test1 DELETE DELETE WHERE (EventTs = 1535698800000) AND (Name = 'xx')

Ok.

0 rows in set. Elapsed: 0.005 sec.
```
exeucte returned ok, but reselect can found this row exists

In `system.mutations` tables:

```
SELECT *
FROM system.mutations

┌─database─┬─table─┬─mutation_id─────────┬─command───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬─────────create_time─┬─block_numbers.partition_id─┬─block_numbers.number─┬─parts_to_do─┬─is_done─┐
│ default  │ test1 │ mutation_170766.txt │ DELETE WHERE (EventTs = 1535698800000) AND (Name = 'xx')                                                                      │ 2018-09-06 16:55:08 │ ['']                       │ [170766]             │           1 │       0 │
│ default  │ test1 │ mutation_170767.txt │ DELETE WHERE (EventTs = 1535698800000) AND (Name = 'xx')                                                                      │ 2018-09-06 16:55:22 │ ['']                       │ [170767]             │           1 │       0 │
└──────────┴───────┴─────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴─────────────────────┴────────────────────────────┴──────────────────────┴─────────────┴─────────┘
```

And try to restart merge task `SYSTEM STOP MERGES; SYSTEM START MERGES`, the result like same.

### env

1. server run with docker. version: `ClickHouse server version 18.10.3 revision 54405`
2. os: `centos7.2`, kernel: `3.10`
3. table test1 ddl like:
```
CREATE TABLE `test1` (
  `EventTs` UInt64,
  `EventTime` DateTime MATERIALIZED toDateTime(round(EventTs/1000)),
  `EventDate` Date MATERIALIZED toDate(EventTime),
  `Name` String,
  `TagKeys` Array(String),
  `TagValues` Array(String)
) ENGINE = MergeTree(EventDate, Name, 8192);
```
4. EventData
```
┌───────EventTs─┬──EventDate─┐
│ 1535698800000 │ 2018-08-31 │
│ 1535698800000 │ 2018-08-31 │
└───────────────┴────────────┘
```

**Comment by ztlpn** [comment] 2018-09-10 11:35
This is a duplicate of #2900 
The bug is fixed in master and the fix will be released shortly.

**Closed by ztlpn** 2018-09-10 11:35 UTC
