### ISSUE TITLE
Received signal Segmentation fault.

### ISSUE THREAD

**Issue by NearTan** [yandex/ClickHouse#5229] opened 2019-05-09 11:25 UTC
**Describe the bug**
ClickHouse crash with a Segment Fault, and without any operation by user. The query(see error message) seems produced by itself(maybe about monitoring).

**How to reproduce**
Can not reproduce.

**ClickHouse server version**
version 19.5.2.6 (official build)

**Error message and/or stacktrace**
```

2019.05.09 18:22:00.535422 [ 4079 ] {453cb8c1-1d6f-4221-9775-6bafae4c5bc2} <Error> executeQuery: std::exception. Code: 1001, type: std::logic_error, e.what() = basic_string::_M_construct null not valid, version = 19.5.2.6 (official build) (from 127.0.0.1:13356) (in query: SELECT DISTINCT arrayJoin(extractAll(name, '[\\w_]{2,}')) AS res FROM (SELECT name FROM system.functions UNION ALL SELECT name FROM system.table_engines UNION ALL SELECT name FROM system.formats UNION ALL SELECT name FROM system.table_functions UNION ALL SELECT name FROM system.data_type_families UNION ALL SELECT name FROM system.settings UNION ALL SELECT concat(func.name, comb.name) FROM system.functions AS func CROSS JOIN system.aggregate_function_combinators AS comb WHERE is_aggregate UNION ALL SELECT name FROM system.databases LIMIT 10000 UNION ALL SELECT DISTINCT name FROM system.tables LIMIT 10000 UNION ALL SELECT DISTINCT name FROM system.columns LIMIT 10000) WHERE notEmpty(res))
2019.05.09 18:22:00.570969 [ 4093 ] {} <Error> BaseDaemon: ########################################
2019.05.09 18:22:00.571009 [ 4093 ] {} <Error> BaseDaemon: (version 19.5.2.6 (official build)) (from thread 4079) Received signal Segmentation fault (11).
2019.05.09 18:22:00.571023 [ 4093 ] {} <Error> BaseDaemon: Address: NULL pointer.
2019.05.09 18:22:00.571030 [ 4093 ] {} <Error> BaseDaemon: Access: read.
2019.05.09 18:22:00.571036 [ 4093 ] {} <Error> BaseDaemon: Unknown si_code.
2019.05.09 18:22:00.698715 [ 4093 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> > >*)+0x18) [0x377fd58]
2019.05.09 18:22:00.698744 [ 4093 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> > > >::_M_erase(std::_Rb_tree_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<DB::IStorage> > >*)+0x24) [0x377fd64]
2019.05.09 18:22:00.698763 [ 4093 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server(DB::DatabaseSnapshotIterator::~DatabaseSnapshotIterator()+0x24) [0x683f634]
2019.05.09 18:22:00.698773 [ 4093 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::TablesBlockInputStream::~TablesBlockInputStream()+0x61) [0x6713131]
2019.05.09 18:22:00.698782 [ 4093 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x47) [0x377f147]
2019.05.09 18:22:00.698793 [ 4093 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::~ExpressionBlockInputStream()+0xb3) [0x6b66ab3]
2019.05.09 18:22:00.698800 [ 4093 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::DistinctBlockInputStream::~DistinctBlockInputStream()+0x745) [0x6d15a85]
2019.05.09 18:22:00.698808 [ 4093 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x47) [0x377f147]
2019.05.09 18:22:00.698815 [ 4093 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::~ExpressionBlockInputStream()+0xb3) [0x6b66ab3]
2019.05.09 18:22:00.698822 [ 4093 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::LimitBlockInputStream::~LimitBlockInputStream()+0x2f5) [0x6781705]
2019.05.09 18:22:00.698830 [ 4093 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::ConvertingBlockInputStream::~ConvertingBlockInputStream()+0x425) [0x6d07285]
2019.05.09 18:22:00.698837 [ 4093 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::FilterBlockInputStream::~FilterBlockInputStream()+0x445) [0x6d23025]
2019.05.09 18:22:00.698847 [ 4093 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x47) [0x377f147]
2019.05.09 18:22:00.698854 [ 4093 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::~ExpressionBlockInputStream()+0xb3) [0x6b66ab3]
2019.05.09 18:22:00.698861 [ 4093 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::DistinctBlockInputStream::~DistinctBlockInputStream()+0x745) [0x6d15a85]
2019.05.09 18:22:00.698869 [ 4093 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x47) [0x377f147]
2019.05.09 18:22:00.698876 [ 4093 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::IBlockInputStream::~IBlockInputStream()+0x9b) [0x378eb9b]
2019.05.09 18:22:00.698883 [ 4093 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::UnionBlockInputStream::~UnionBlockInputStream()+0xf2) [0x68bace2]
2019.05.09 18:22:00.698890 [ 4093 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::DistinctBlockInputStream::~DistinctBlockInputStream()+0x745) [0x6d15a85]
2019.05.09 18:22:00.698897 [ 4093 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x47) [0x377f147]
2019.05.09 18:22:00.698904 [ 4093 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::~ExpressionBlockInputStream()+0xb3) [0x6b66ab3]
2019.05.09 18:22:00.698911 [ 4093 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::ProcessListEntry::~ProcessListEntry()+0x2ee) [0x696753e]
2019.05.09 18:22:00.698919 [ 4093 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+0x47) [0x377f147]
2019.05.09 18:22:00.698931 [ 4093 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server(DB::BlockIO::operator=(DB::BlockIO const&)+0x6c) [0x378e57c]
2019.05.09 18:22:00.698938 [ 4093 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(DB::QueryState::reset()+0x1a2) [0x378f5d2]
2019.05.09 18:22:00.698946 [ 4093 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server(DB::TCPHandler::runImpl()+0x886) [0x378c346]
2019.05.09 18:22:00.698953 [ 4093 ] {} <Error> BaseDaemon: 26. /usr/bin/clickhouse-server(DB::TCPHandler::run()+0x2b) [0x378c85b]
2019.05.09 18:22:00.698960 [ 4093 ] {} <Error> BaseDaemon: 27. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x7500d6f]
2019.05.09 18:22:00.698968 [ 4093 ] {} <Error> BaseDaemon: 28. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0xe9) [0x75014a9]
2019.05.09 18:22:00.698975 [ 4093 ] {} <Error> BaseDaemon: 29. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x81) [0x75b45e1]
2019.05.09 18:22:00.698982 [ 4093 ] {} <Error> BaseDaemon: 30. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x75b07a8]
2019.05.09 18:22:00.698991 [ 4093 ] {} <Error> BaseDaemon: 31. /usr/bin/clickhouse-server() [0xb27522f]
2019.05.09 18:22:00.698998 [ 4093 ] {} <Error> BaseDaemon: 32. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7fe68ff356db]

```
**Additional context**
I check some previous issues like https://github.com/yandex/ClickHouse/issues/4880 and seems they are not the same.

**Comment by den-crane** [comment] 2019-05-09 11:34
duplicate of https://github.com/yandex/ClickHouse/issues/5066
Just use `clickhouse-client -A ` or downgrade to 19.4.3.11.

**Comment by NearTan** [comment] 2019-05-09 12:30
@den-crane Thanks for your information.

**Closed** 2019-05-10 08:38 UTC
Labels: bug, duplicate
