### ISSUE TITLE
BackgroundProcessingPool pottential improvements

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#2281] opened 2018-04-25 10:32 UTC
Hello,

Looking over the code in BackgroundProcessingPool I have a feeling that's room for improvements.

I wrote a script that creates 10k MergeTree tables and at every 10 seconds cpu goes crazy, even if there is no activity.

Looking to the code I spotted that tasks that are inside the BackgroundProcessingPool are scheduled after 10 seconds in case 
they return that no work was performed. 

Any reason for this approach ? I mean in case there is no work to be performed on the last run and no new writes arrived 
I suppose that will never perform any work any longer, so calling it in loop is pointless. I'm right ?

Also from what I see when a new block is written the task is calling wake() function which schedules that tasks right away.

So I'm wonder if a better approach will be to reschedule the tasks only:
	1. when last time reported that work was performed
	2. when new blocks are written
	
Do you see any problem with this approach ?

Silviu

**Comment by silviucpp** [comment] 2018-05-08 10:13
@alexey-milovidov  any thought on this ?

**Comment by alexey-milovidov** [comment] 2018-07-05 21:41
First, we can add random part for wait intervals. For example, instead of 10 seconds it can be resheduled in an interval, uniformly distributed in 8..12 seconds.

Next we can review all places when some task is rescheduled unconditionally.

> So I'm wonder if a better approach will be to reschedule the tasks only:
1. when last time reported that work was performed
2. when new blocks are written

This approach should work, but we have to review every single case.

**Comment by silviucpp** [comment] 2018-07-06 07:29
Hello,

Thanks for your feedback ! I'll take a look soon on this and add support for exponential backoff. Should I add the interval in a config setting ? or I can hardcode between 8 and 12 ?

For my personal knowledge can you please elaborate a bit why "It's important to select merges even when there are no writes to a table" and last run returned that there is no work to be done ?

Silviu

**Comment by alexey-milovidov** [comment] 2018-07-06 15:47
> Should I add the interval in a config setting ? or I can hardcode between 8 and 12?

You can just put constant in code, similar to
```
static const auto MERGE_SELECTING_SLEEP_MS        = 5 * 1000;
```

> For my personal knowledge can you please elaborate a bit why "It's important to select merges even when there are no writes to a table" and last run returned that there is no work to be done ?

Example 1:

Suppose at some moment of time you have a table with many (example: 1000) parts.
SELECT queries are slow. These parts need to be merged to speed up queries.
But you already have finished INSERTs and parts have no chance to be selected for merges.

Example 2:

You do large INSERT SELECT or large data upload. Data is loading into a table as fast as possible in a single thread. During this INSERT you have 25 parts in a table in average. After INSERT is finished, you also have 25 parts.
But you want for parts to be eventually merged (for example, to just 5 parts) after INSERT is finished, in background.

**Comment by filimonov** [comment] 2018-07-06 16:10
As i understand @silviucpp propose to stop triggering background merges if previous background merge run found that there are no parts to merge (everything was already merged)

I.e. there was 10 parts
1) first background merge merged 8 of them, and save flag "some work was done, more merges can be needed", 3 parts now. 
2) next background merge merged 3 parts, but they are too big to merge, so we can't do anything else, and reset the flag. That means that no work needed for that table, no background tasks should be executed till new data will arrive.
3) then new insert arrive - it set the flag back again, and background jobs will be executed again.

**Comment by silviucpp** [comment] 2018-07-06 17:12
@filimonov Yes exactly. This is my point. 

So basically after each new write the merge event is scheduled (as it is now) and that event schedules itself until return that there is no more jobs to  be run on that table. In this moment the job  already returns this information but logic is:
- if there are still parts to be merged schedules immediately
- if there are no parts to be merged schedules after 10 seconds

Silviu

**Comment by alexey-milovidov** [comment] 2018-07-06 18:37
Selecting parts to merge is dependent on age of parts.
See `SimpleMergeSelector`.

For example, some parts may be not selected for merge right now, but they will be selected after few minutes, even if the set of parts was not changed.

**Comment by silviucpp** [comment] 2018-07-06 18:46
OK this is the detail that makes the difference :) Then only improvement we can make is to apply the  exponential backoff

**Comment by alexey-milovidov** [comment] 2018-07-08 00:41
This script creates 10 000 MergeTree tables sequentially:
```
clickhouse-client --query="CREATE DATABASE multiple_mergetrees"
seq 1 10000 | sed -r -e 's/^.+$/CREATE TABLE multiple_mergetrees.table\0 (x UInt8) ENGINE = MergeTree ORDER BY x;/' | clickhouse-client -n
```
(but doesn't write anything into these tables)

It takes 4 minutes.
After creation, clickhouse-server constantly eats about 0..5% of single CPU core.
No observable spikes in CPU usage.

**Comment by alexey-milovidov** [comment] 2018-07-08 00:46
Now lets insert something into all of these tables:
```
seq 1 10000 | sed -r -e 's/^.+$/INSERT INTO multiple_mergetrees.table\0 VALUES (0)/' | clickhouse-client -n
```

It takes only 5 seconds to execute 10 000 inserts.
After insertion, there is no increase in CPU usage. And still no spikes.

**Comment by alexey-milovidov** [comment] 2018-07-08 00:48
Now I'll create 100 000 MergeTree tables, all in parallel in 16 threads:
```
seq 10001 100000 | sed -r -e 's/^.+$/CREATE TABLE multiple_mergetrees.table\0 (x UInt8) ENGINE = MergeTree ORDER BY x;/' | clickhouse-benchmark -c16
```

**Comment by alexey-milovidov** [comment] 2018-07-08 00:56
Now clickhouse-server constantly eats about 10..50% of single CPU core and no spikes exist.

**Comment by alexey-milovidov** [comment] 2018-07-08 02:37
CPU time is spent in `statfs` system call, that is used to check free space before assigning merge
and in `readdir` for `DB::MergeTreeData::clearOldTemporaryDirectories`, `DB::MergeTreeData::clearOldPartsFromFilesystem`.

Also some time is spent in `DB::Context::getPartLog` for getting configuration value.

**Comment by alexey-milovidov** [comment] 2018-07-08 03:16
I cannot reproduce the issue that you describe.
Maybe it exists if you run debug build. Or if you run under Mac OS.

**Comment by alexey-milovidov** [comment] 2018-07-08 03:16
After this commit 3445c78, CPU usage for 100 000 tables drops to less than 10% of one CPU core.

**Comment by alexey-milovidov** [comment] 2018-07-08 03:34
When I do test:
```
seq 1 100000 | sed -r -e 's/^.+$/INSERT INTO multiple_mergetrees.table\0 SELECT rand()/' | clickhouse-benchmark -c16
```
I see periodic stalls for 10s of seconds.

**Comment by alexey-milovidov** [comment] 2018-07-08 05:46
> I see periodic stalls for 10s of seconds.

Stalls are in Linux kernel:

```
[pid 663052] <... open resumed> )       = 8 <59.698087>
[pid 241203] <... unlink resumed> )     = 0 <60.287390>
[pid 241202] <... unlink resumed> )     = 0 <60.363974>
[pid 241200] <... mkdir resumed> )      = 0 <60.499555>
[pid 241201] <... mkdir resumed> )      = 0 <60.506257>
[pid 241198] <... mkdir resumed> )      = 0 <60.498695>
[pid 241197] <... mkdir resumed> )      = 0 <60.472137>
[pid 241199] <... mkdir resumed> )      = 0 <60.472145>
[pid 241196] <... mkdir resumed> )      = 0 <60.979219>
[pid 241195] <... mkdir resumed> )      = 0 <60.963000>
[pid 241194] <... mkdir resumed> )      = 0 <60.964198>
[pid 241193] <... mkdir resumed> )      = 0 <60.963490>
[pid 241192] <... mkdir resumed> )      = 0 <60.965698>
[pid 241191] <... mkdir resumed> )      = 0 <60.940064>
[pid 241190] <... mkdir resumed> )      = 0 <60.958177>
[pid 241189] <... mkdir resumed> )      = 0 <60.931069>
[pid 241188] <... mkdir resumed> )      = 0 <60.941951>
```

**Closed** 2018-07-08 05:49 UTC
Labels: enhancement, performance
