### ISSUE TITLE
Poco::Exception. Code: 1000, e.code() = 0

### ISSUE THREAD

**Issue by eagle1981** [yandex/ClickHouse#4047] opened 2019-01-14 02:35 UTC
Using docker clickhouse-server:latest

After upgrade - we have many error-log entries such as:

2019.01.14 02:24:10.831297 [ 17 ] {} <Error> graphite.metrics_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received
2019.01.14 02:24:20.916719 [ 7 ] {} <Error> graphite.metrics_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::
Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received

2019.01.14 02:24:26.813686 [ 4 ] {} <Error> graphite.data_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received

2019.01.14 02:24:32.580035 [ 16 ] {} <Error> graphite.data_lr (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received, e.what() = No message received

**Comment by filimonov** [comment] 2019-01-14 10:16
Most probably duplicate of #3891. The issue was fixed in master, but not released yet.

**Comment by eagle1981** [comment] 2019-01-14 10:56
Looks like it is. Any plans to promote changes to :latest ?

**Comment by filimonov** [comment] 2019-01-14 12:19
When new version will be ready it will be released. Stay tuned :)
For now, you can use 18.14.19, or build latest with needed fixes by your own.

**Comment by zzn01** [comment] 2019-01-21 08:11
what's the affection of this error? Is it safe to ignore?

**Comment by ztlpn** [comment] 2019-01-29 20:04
@andywow reports that the `No message received` error is still present on 19.1.6. @alesapin can you take a look?

**Comment by alesapin** [comment] 2019-01-30 10:38
@andywow Can you describe in more details? Maybe provide some logs? We got `No message received` error in our tests, but in this PR https://github.com/yandex/ClickHouse/pull/3932 problem was fixed. Maybe you have other problem with same 'awesome' message.

**Comment by alesapin** [comment] 2019-02-04 10:36
@andywow Unfortunately I can't get any useful information from your log :( Seems like you get some other problem. Can you describe your shard configuration? Do you update all shard servers to 19.1.6? Maybe we can discuss this issue in details in telegram?

**Comment by evgeny-l** [comment] 2019-02-19 20:12
@alesapin 
Hi! Seems like I'm experiencing similar issue with my ClickHouse setup.

ClickHouse error log got spammed with messages like:

019.02.19 20:09:33.781020 [ 2 ] {} <Error> events.bid_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:09:47.192792 [ 16 ] {} <Error> events.commercial_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:09:48.945355 [ 11 ] {} <Error> events.commercial_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:09:53.439429 [ 3 ] {} <Error> events.commercial_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:09:57.621721 [ 10 ] {} <Error> events.video_events_summing (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:10:06.996773 [ 16 ] {} <Error> events.integration_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:10:16.405888 [ 10 ] {} <Error> events.commercial_events_summing (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:10:30.415479 [ 9 ] {} <Error> events.video_events_summing (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:10:48.778418 [ 9 ] {} <Error> events.video_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.02.19 20:10:49.174598 [ 6 ] {} <Error> events.commercial_events (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received

If I can assist you somehow in the way to fix that, you can contact me in telegram @eleksunin.

**Comment by mikeeremin** [comment] 2019-03-13 08:37
19.3.7 - still present.

**Comment by sunadm** [comment] 2019-03-14 08:26
Me too,
After upgrade from 18.14 to 19.3.5.

Change log mode to trace: 

```
2019.03.14 16:21:21.533589 [ 35 ] {} <Debug> report.amg_wms_stock_flow_local (ReplicatedMergeTreeQueue): Pulling 1 entries to queue: log-0003080762 - log-0003080762
2019.03.14 16:21:21.538431 [ 35 ] {} <Debug> report.amg_wms_stock_flow_local (ReplicatedMergeTreeQueue): Pulled 1 entries to queue.
2019.03.14 16:21:21.543065 [ 6 ] {} <Debug> report.amg_wms_stock_flow_local (StorageReplicatedMergeTree): Fetching part 201903_203782_203782_0 from /clickhouse/tables/dplus/01/amg_wms_stock_flow/replicas/clickhouse-02
2019.03.14 16:21:21.544489 [ 6 ] {} <Trace> ReadWriteBufferFromHTTP: Sending request to http://clickhouse-02:9009/?endpoint=DataPartsExchange%3A%2Fclickhouse%2Ftables%2Fdplus%2F01%2Famg_wms_stock_flow%2Freplicas%2Fclickhouse-02&part=201903_203782_203782_0&compress=false
2019.03.14 16:21:21.544630 [ 6 ] {} <Error> report.amg_wms_stock_flow_local (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
```

**Comment by madm1keru** [comment] 2019-03-22 06:26
I see the same flood in logs, even at testing 19.4.2.4.

`
2019.03.22 08:43:01.515845 [ 5 ] {} <Error> SrcData.TTAdmLog (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:43:08.441357 [ 10 ] {} <Error> SrcData.TTAdmLog (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:43:25.061637 [ 16 ] {} <Error> SrcData.TTAdmLog (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:43:26.528284 [ 14 ] {} <Error> SrcData.TTAdmLog (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:44:25.361261 [ 6 ] {} <Error> SrcData.TTStatBase (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:44:25.993816 [ 3 ] {} <Error> SrcData.TTStatBase (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:44:32.062546 [ 4 ] {} <Error> SrcData.TTStatBase (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received
2019.03.22 08:44:32.629462 [ 17 ] {} <Error> SrcData.TTStatBase (StorageReplicatedMergeTree): auto DB::StorageReplicatedMergeTree::queueTask()::(anonymous class)::operator()(DB::StorageReplicatedMergeTree::LogEntryPtr &) const: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = No message received`

**Comment by nvartolomei** [comment] 2019-03-27 17:18
Hitting same exception with v19.1.15. Node from which replication is tried does not log anything.

**Comment by nvartolomei** [comment] 2019-03-28 16:53
@alesapin any clues why would this happen? I'm pretty confident that this is related to connection pooling and getting a closed/close-wait connection from the pool :)

**Comment by alesapin** [comment] 2019-03-29 18:23
Sorry for ignoring this issue :( I didn't receive any notifications from GitHub.

**Fix:** https://github.com/yandex/ClickHouse/pull/4856.
**Work around:** set `<keep_alive_timeout>` in `config.xml` to 8 seconds.

**Closed** 2019-03-29 20:08 UTC

**Comment by bzon** [comment] 2019-04-24 09:54
I'm using version 19.4.3. This issue still happens even after running `SYSTEM DROP DNS CACHE` and `<keep_alive_timeout>` in `config.xml` with 8 seconds.

```
<Error> default.table_sharded (StorageReplicatedMergeTree): DB::StorageReplicatedMergeTree::queueTask()::<lambda(DB::StorageReplicatedMergeTree::LogEntryPtr&)>: Poco::Exception. Code: 1000, e.code() = 0, e.displayText() = Timeout: connect timed out: 10.8.6.25:9009
```

The exact error is `Timeout: connect timed out: 10.8.6.25:9009`. That IP is the old IP of the previous container that restarted. My solution is to restart this Clickhouse container and run `SYSTEM DROP DNS CACHE` in all the Clickhouse containers.
