### ISSUE TITLE
Support GCC 9

### ISSUE THREAD

**Issue by excitoon** [yandex/ClickHouse#5717] opened 2019-06-22 08:23 UTC
```/home/ex/ClickHouse/libs/libglibc-compatibility/glibc-compatibility.c:134:5: error: ‘__isoc99_sscanf’ specifies less restrictive attributes than its target ‘
sscanf’: ‘nonnull’, ‘nothrow’ [-Werror=missing-attributes]
  134 | int __isoc99_sscanf(const char *str, const char *format, ...) __attribute__((weak, alias("sscanf")));
      |     ^~~~~~~~~~~~~~~
/home/ex/ClickHouse/libs/libglibc-compatibility/glibc-compatibility.c:124:5: note: ‘__isoc99_sscanf’ target declared here
  124 | int sscanf(const char *restrict s, const char *restrict fmt, ...)
      |     ^~~~~~
cc1: all warnings being treated as errors
make[2]: *** [libs/libglibc-compatibility/CMakeFiles/glibc-compatibility.dir/build.make:63: libs/libglibc-compatibility/CMakeFiles/glibc-compatibility.dir/glibc-compatibility.c.o] Error 1
```

**Comment by excitoon** [comment] 2019-06-22 08:52
FYI @kmeaw current AUR build is broken :(

**Comment by Felixoid** [comment] 2019-06-27 07:04
Fixed in aur:clickhouse-static

**Comment by alexey-milovidov** [comment] 2019-06-27 13:53
This issue is not related to gcc-9.
It is related to the newer version of libc in your system.

What is the output of `ldd --version`?

**Comment by Felixoid** [comment] 2019-06-27 14:08
```
ldd (GNU libc) 2.29
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by alexey-milovidov** [comment] 2019-06-27 14:13
Ok, thank you!

PS.
```
milovidov@milovidov-Latitude-E7470:~$ docker run --rm -it ubuntu:bionic ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
milovidov@milovidov-Latitude-E7470:~$ docker run --rm -it ubuntu:cosmic ldd --version
ldd (Ubuntu GLIBC 2.28-0ubuntu1) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
milovidov@milovidov-Latitude-E7470:~$ docker run --rm -it ubuntu:disco ldd --version
Unable to find image 'ubuntu:disco' locally
disco: Pulling from library/ubuntu
29c2f229a128: Pull complete 
5d724aeeb884: Pull complete 
60682405dd89: Pull complete 
3b9cd0202583: Pull complete 
Digest: sha256:db265801d395a88e15ed4eac372693012275a1a181d1032ebb0cefdd01e5a99f
Status: Downloaded newer image for ubuntu:disco
ldd (Ubuntu GLIBC 2.29-0ubuntu2) 2.29
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by alexey-milovidov** [comment] 2019-06-27 14:24
> This issue is not related to gcc-9.
It is related to the newer version of libc in your system.

Actually I was wrong. The issue is related to more strict attributes for builtin function in gcc-9.

**Closed** 2019-06-27 17:24 UTC
Labels: build

**Comment by excitoon** [comment] 2019-06-27 20:47
Thank you!

**Comment by mariusa** [comment] 2019-06-28 15:51
@alexey-milovidov Thanks! How about removing gcc7 from https://clickhouse.yandex/docs/en/development/build/ ?

**Comment by alexey-milovidov** [comment] 2019-06-28 17:14
@mariusa Ok.
