### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by meagon** [yandex/ClickHouse#140] opened 2016-10-18 03:23 UTC
i got the below error while compilin ths source ?

```
Scanning dependencies of target PocoZip
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:132:71: error: conflicting declaration ‘void* (* volatile __malloc_hook)(size_t, const void*)’
 void* (* MALLOC_HOOK_MAYBE_VOLATILE __malloc_hook)(size_t, const void*)
                                                                       ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:165:16: note: previous declaration as ‘void* (* __malloc_hook)(size_t, const void*)’
 extern void *(*__malloc_hook) __MALLOC_PMT ((size_t __size,
                ^~~~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:134:79: error: conflicting declaration ‘void* (* volatile __realloc_hook)(void*, size_t, const void*)’
 void* (* MALLOC_HOOK_MAYBE_VOLATILE __realloc_hook)(void*, size_t, const void*)
                                                                               ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:167:16: note: previous declaration as ‘void* (* __realloc_hook)(void*, size_t, const void*)’
 extern void *(*__realloc_hook) __MALLOC_PMT ((void *__ptr, size_t __size,
                ^~~~~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:136:67: error: conflicting declaration ‘void (* volatile __free_hook)(void*, const void*)’
 void (* MALLOC_HOOK_MAYBE_VOLATILE __free_hook)(void*, const void*)
                                                                   ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:163:15: note: previous declaration as ‘void (* __free_hook)(void*, const void*)’
 extern void (*__free_hook) __MALLOC_PMT ((void *__ptr,
               ^~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:138:80: error: conflicting declaration ‘void* (* volatile __memalign_hook)(size_t, size_t, const void*)’
 void* (* MALLOC_HOOK_MAYBE_VOLATILE __memalign_hook)(size_t,size_t, const void*)
                                                                                ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/include/gperftools/tcmalloc.h:49:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:91:
/usr/include/malloc.h:169:16: note: previous declaration as ‘void* (* __memalign_hook)(size_t, size_t, const void*)’
 extern void *(*__memalign_hook) __MALLOC_PMT ((size_t __alignment,
                ^~~~~~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:85:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:132:71: error: conflicting declaration ‘void* (* volatile __malloc_hook)(size_t, const void*)’
 void* (* MALLOC_HOOK_MAYBE_VOLATILE __malloc_hook)(size_t, const void*)
                                                                       ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:46:0:
/usr/include/malloc.h:165:16: note: previous declaration as ‘void* (* __malloc_hook)(size_t, const void*)’
 extern void *(*__malloc_hook) __MALLOC_PMT ((size_t __size,
                ^~~~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:85:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:134:79: error: conflicting declaration ‘void* (* volatile __realloc_hook)(void*, size_t, const void*)’
 void* (* MALLOC_HOOK_MAYBE_VOLATILE __realloc_hook)(void*, size_t, const void*)
                                                                               ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:46:0:
/usr/include/malloc.h:167:16: note: previous declaration as ‘void* (* __realloc_hook)(void*, size_t, const void*)’
 extern void *(*__realloc_hook) __MALLOC_PMT ((void *__ptr, size_t __size,
                ^~~~~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:85:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:136:67: error: conflicting declaration ‘void (* volatile __free_hook)(void*, const void*)’
 void (* MALLOC_HOOK_MAYBE_VOLATILE __free_hook)(void*, const void*)
                                                                   ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:46:0:
/usr/include/malloc.h:163:15: note: previous declaration as ‘void (* __free_hook)(void*, const void*)’
 extern void (*__free_hook) __MALLOC_PMT ((void *__ptr,
               ^~~~~~~~~~~
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/libc_override.h:79:0,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/tcmalloc.cc:156,
                 from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:85:
/tmp/ClickHouse/contrib/libtcmalloc/src/libc_override_glibc.h:138:80: error: conflicting declaration ‘void* (* volatile __memalign_hook)(size_t, size_t, const void*)’
 void* (* MALLOC_HOOK_MAYBE_VOLATILE __memalign_hook)(size_t,size_t, const void*)
                                                                                ^
In file included from /tmp/ClickHouse/contrib/libtcmalloc/src/debugallocation.cc:46:0:
/usr/include/malloc.h:169:16: note: previous declaration as ‘void* (* __memalign_hook)(size_t, size_t, const void*)’
 extern void *(*__memalign_hook) __MALLOC_PMT ((size_t __alignment,
                ^~~~~~~~~~~~~~~
[ 47%] Built target PocoData

```

**Comment by alexey-milovidov** [comment] 2016-10-20 03:17
This is duplicate of https://github.com/yandex/ClickHouse/issues/98#issuecomment-244261639

**Comment by alexey-milovidov** [comment] 2016-10-20 03:54
Updated tcmalloc library to latest version, which was removed usage of obsolete malloc hooks.

**Closed** 2017-02-08 10:33 UTC
Labels: build
