### ISSUE TITLE
Unable to update Enum column

### ISSUE THREAD

**Issue by VaSoTula** [yandex/ClickHouse#6778] opened 2019-09-02 14:46 UTC
The following query:
`alter table SomeTable update Device = 'Other' where Id = 1`

causes the following error:
> SQL Error [386]: ClickHouse exception, code: 386, host ***, port: 8123; Code: 386, e.displayText() = DB::Exception: There is no supertype for types String, Enum8('Other' = 0, 'Phone' = 1, 'Tablet' = 2, 'Desktop' = 3) because some of them are String/FixedString and some of them are not (version 19.11.3.11)

The following query:
`alter table SomeTable update Device = 0 where Id = 1`

causes the same error.

**Comment by filimonov** [comment] 2019-09-03 10:10
Try that:
```
alter table SomeTable update Device=CAST('Other', 'Enum8(\'Other\' = 0, \'Phone\' = 1, \'Tablet\' = 2, \'Desktop\' = 3)') ...
```

**Comment by filimonov** [comment] 2019-09-03 10:12
It's a duplicate of: https://github.com/yandex/ClickHouse/issues/4165

**Closed by filimonov** 2019-09-03 10:12 UTC
Labels: bug, comp-mutations, duplicate
