### ISSUE TITLE
Is this an expected corrupt when an OOM occurs

### ISSUE THREAD

**Issue by fancyqlx** [yandex/ClickHouse#4452] opened 2019-02-20 07:20 UTC
Hi
Recently, I met a corrupt when the clickhouse server is killed because of OOM. The log shows that it may be caused by unjoined threads. It may be an expect behavior if the main thread is killed and the threads in thread pool have not joined. BUT, the problem is that a coredump need to write coredump file and it always slows the server. So, is this an expected corrupt and is there any ways to fix this problem. 
![image](https://user-images.githubusercontent.com/6196299/53073403-e6de4f80-3522-11e9-98e5-dcb1d57d844c.png)

**Comment by ztlpn** [comment] 2019-02-21 15:31
The problem is that during aggregation a thread pool is created and if one of the threads cannot be created (e.g. when there is not enough memory), other threads are not joined which causes `std::terminate`.

This was fixed in #3956 (available since 19.1.6)

**Closed by ztlpn** 2019-02-21 15:31 UTC
Labels: bug, issue

**Comment by fancyqlx** [comment] 2019-02-22 07:54
@ztlpn thanks
