### ISSUE TITLE
Is there any way to stop an error mutation?

### ISSUE THREAD

**Issue by 5cmpersec** [yandex/ClickHouse#3859] opened 2018-12-18 10:51 UTC
I recently triggered an ALTER mutation on a relatively big table, then an error happens due to several bugs on clickhouse-server. How can I stop the mutation without dropping the table?

**Comment by ztlpn** [comment] 2018-12-18 12:09
Closing as a duplicate of #3782, please see https://github.com/yandex/ClickHouse/issues/3782#issuecomment-445228934

**Closed by ztlpn** 2018-12-18 12:09 UTC
