### ISSUE TITLE
Slow performance on jagged array indexing with empty inner array

### ISSUE THREAD

**Issue by fireya** [yandex/ClickHouse#1889] opened 2018-02-12 15:38 UTC
Hello!
I have noticed strange performance issue when using jagged array in clickhouse. 
1st query:
`select [[1],[2]][D1] as c1 from data100m group by c1`
time: 1.5 seconds

2nd query:
`select [[],[2]][D1] as c1 from data100m group by c1`
time: 5 seconds

table has 100 million rows. Column D1 doesn't contain value 1, so first element of array will not be used.
But performance is signifficantly different.
Is this a bug?

**Comment by alexey-milovidov** [comment] 2018-02-12 21:08
Yes, the performance is very different. Due to some implementation details, array `[[],[2]]` is not treated as constant, and less efficient code path is selected.

Although this is not a bug, we should improve performance in this case.

**Comment by alexey-milovidov** [comment] 2018-02-12 21:09
Fixed in master.

**Closed** 2018-02-12 21:09 UTC
