### ISSUE TITLE
CH won't start after upgrade to 1.1.54387 

### ISSUE THREAD

**Issue by den-crane** [yandex/ClickHouse#2565] opened 2018-06-26 20:07 UTC
We have several internal dictionaries and database with Dictionary engine.

```
      <clickhouse>
        <host>localhost</host>
        <port>9000</port>
```
 /var/log/clickhouse-server/clickhouse-server.log
```
2018.06.26 20:01:05.395727 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.395742 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.395808 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №2, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.395818 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.395906 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №3, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.395921 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.395984 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.395994 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.396055 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №2, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.396064 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.396125 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №3, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.397414 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.397486 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №1, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, ::1), e.what() = DB::NetException
2018.06.26 20:01:05.397497 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
......
018.06.26 20:01:05.401607 [ 1 ] <Trace> Connection (localhost:9000, ::1): Connecting. Database: dw. User: default
2018.06.26 20:01:05.401665 [ 1 ] <Warning> ConnectionPoolWithFailover: Connection failed at try №3, reason: Code: 210, e.displayText() = DB::NetException: Connection refused: (localhost:9000, :
:1), e.what() = DB::NetException
.....
2018.06.26 20:01:08.773623 [ 1 ] <Debug> Application: Destroyed global context.
2018.06.26 20:01:08.773732 [ 1 ] <Error> Application: Timeout
2018.06.26 20:01:08.773751 [ 1 ] <Information> Application: shutting down
2018.06.26 20:01:08.773757 [ 1 ] <Debug> Application: Uninitializing subsystem: Logging Subsystem
2018.06.26 20:01:08.773810 [ 4 ] <Information> BaseDaemon: Stop SignalListener thread
```

Workaround:  <http_connection_timeout>5</http_connection_timeout>

**Comment by filimonov** [comment] 2018-06-28 06:56
I also always have those warnings when server starts, but it does not shut down.
May be because i have no Dictionary database?

**Comment by alexey-milovidov** [comment] 2019-01-28 16:30
Duplicate of #2870

**Closed** 2019-02-05 09:55 UTC
