### ISSUE TITLE
Improve documentation of hex function or support signed numbers

### ISSUE THREAD

**Issue by StarWix** [yandex/ClickHouse#1476] opened 2017-11-10 13:41 UTC
from: https://clickhouse.yandex/docs/en/single/index.html#hex
> hex
> Accepts a string, number, date, or date with time.

```
SELECT hex(1.)

Received exception from server:
Code: 43. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Illegal type Float64 of argument of function hex.

SELECT hex(-1)

Received exception from server:
Code: 43. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Illegal type Int8 of argument of function hex.
```
Is it by design?

**Comment by alexey-milovidov** [comment] 2017-11-11 00:57
This is by design.

For float, the user could expect one of two possibilities:

1. Format with sign and point, example: `-AB.CDE`. That's unusual, but consistent with hex behaviour for unsigned integers.

2. Format native representation of number as bytes in memory in hex. That's easy, but will be inconsistent, because unsigned numbers are formatted in big endian.

Let's compare with implementation in Python:
```
>>> hex(1)                                                                                                                                                                                                                                         
'0x1'                                                                                                                                                                                                                                                
>>> hex(1.1)                                                                                                                                                                                                                                         
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: hex() argument can't be converted to hex
>>> hex(-1)
'-0x1'
>>>
```

We should fix the documentation.

**Comment by alexey-milovidov** [comment] 2017-11-12 00:44
https://github.com/yandex/ClickHouse/commit/e611e1cc6659526bf519e344f3b81c7066779ca9

**Closed by alexey-milovidov** 2017-11-12 00:44 UTC
