### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by digitalist** [yandex/ClickHouse#110] opened 2016-09-12 19:26 UTC
[ 85%] Building CXX object dbms/CMakeFiles/dbms.dir/src/Parsers/ASTSelectQuery.cpp.o
/data/Downloads/github/ClickHouse/dbms/src/Dictionaries/ComplexKeyHashedDictionary.cpp: In member function ‘void DB::ComplexKeyHashedDictionary::getUInt64(const string&, const ConstColumnPlainPtrs&, const DataTypes&, DB::UInt64, DB::PaddedPODArray<long unsigned int>&) const’:
/data/Downloads/github/ClickHouse/dbms/src/Dictionaries/ComplexKeyHashedDictionary.cpp:505:1: internal compiler error: Segmentation fault
 }

master branch, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
AMD Phenom II 1090T without SSE 4.2 (could it be the source of the problem?)

**Comment by digitalist** [comment] 2016-09-12 19:27
I should try release branch though, so close this issue, if you found the bug

**Comment by goranc** [comment] 2016-09-13 11:27
I also have problem with build on Ubuntu 16.04
[ 93%] Building CXX object dbms/CMakeFiles/dbms.dir/src/Functions/FunctionsArray.cpp.o
g++-5: internal compiler error: Killed (program cc1plus)

If I can assist in resolving the issue, I'll be glad to help.

**Comment by alexey-milovidov** [comment] 2016-09-13 20:55
It is two different issues.

1. 
> g++-5: internal compiler error: Killed (program cc1plus)

It means that child program was killed. Usually it is caused by OOM Killer due to not enough memory in the system. See `dmesg` or `/var/log/kern.log`.

To fix this problem:
- lower number of build threads: for example, run `make` instead of `make -j4`;
- close some memory hungry programs like firefox, chromium;
- mind that build requires about 4 GB of memory.

2. 
> internal compiler error: Segmentation fault
> without SSE 4.2 (could it be the source of the problem?)

It could be the source of problem, but the chance is small.
Try to update to GCC 6. Also you could use recent clang (3.9 or trunk).

**Comment by digitalist** [comment] 2016-09-14 09:28
thanks, I'll check this later today

**Comment by goranc** [comment] 2016-09-14 09:48
Thanks for your answer.
What I did was:
- increased memory to 8GB
- upgraded gcc form 5.4.0 to 5.4.1 (without success to compile)
- upgraded gcc to 6.1.1 (successfully compiled and built deb packages)

**Closed** 2016-09-15 17:34 UTC
