### ISSUE TITLE
core dump(join)

### ISSUE THREAD

**Issue by wuyanxing001** [yandex/ClickHouse#3698] opened 2018-11-29 10:16 UTC
2018.11.29 18:13:41.964978 [ 2 ] {} <Error> BaseDaemon: ########################################
2018.11.29 18:13:41.965061 [ 2 ] {} <Error> BaseDaemon: (from thread 37) Received signal Segmentation fault (11).
2018.11.29 18:13:41.965078 [ 2 ] {} <Error> BaseDaemon: Address: 0x7ffb665ff000
2018.11.29 18:13:41.965090 [ 2 ] {} <Error> BaseDaemon: Access: read.
2018.11.29 18:13:41.965102 [ 2 ] {} <Error> BaseDaemon: Attempted access has violated the permissions assigned to the memory area.
2018.11.29 18:13:42.014650 [ 2 ] {} <Error> BaseDaemon: 0. clickhouse-server(memcpy+0xe3) [0x9e5cd93]
2018.11.29 18:13:42.014691 [ 2 ] {} <Error> BaseDaemon: 1. clickhouse-server(void DB::writeAnyEscapedString<(char)39>(char const*, char const*, DB::WriteBuffer&)+0x1df) [0x316e82f]
2018.11.29 18:13:42.014705 [ 2 ] {} <Error> BaseDaemon: 2. clickhouse-server(DB::BlockOutputStreamFromRowOutputStream::write(DB::Block const&)+0xab) [0x7c13dbb]
2018.11.29 18:13:42.014714 [ 2 ] {} <Error> BaseDaemon: 3. clickhouse-server(DB::MaterializingBlockOutputStream::write(DB::Block const&)+0x709) [0x7904599]
2018.11.29 18:13:42.014739 [ 2 ] {} <Error> BaseDaemon: 4. clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0xc1) [0x6af44b1]
2018.11.29 18:13:42.014763 [ 2 ] {} <Error> BaseDaemon: 5. clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x56b) [0x76926fb]
2018.11.29 18:13:42.014780 [ 2 ] {} <Error> BaseDaemon: 6. clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x3169) [0x30a2809]
2018.11.29 18:13:42.014789 [ 2 ] {} <Error> BaseDaemon: 7. clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3be) [0x30a4e2e]
2018.11.29 18:13:42.014798 [ 2 ] {} <Error> BaseDaemon: 8. clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x332) [0x9b703e2]
2018.11.29 18:13:42.014806 [ 2 ] {} <Error> BaseDaemon: 9. clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x9b68c8f]
2018.11.29 18:13:42.014814 [ 2 ] {} <Error> BaseDaemon: 10. clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x16a) [0x9b6906a]
2018.11.29 18:13:42.014822 [ 2 ] {} <Error> BaseDaemon: 11. clickhouse-server(Poco::PooledThread::run()+0x77) [0x9c85e47]
2018.11.29 18:13:42.014830 [ 2 ] {} <Error> BaseDaemon: 12. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x9c819b8]
2018.11.29 18:13:42.014837 [ 2 ] {} <Error> BaseDaemon: 13. clickhouse-server() [0xa3db80f]
2018.11.29 18:13:42.014847 [ 2 ] {} <Error> BaseDaemon: 14. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ffb8504b184]

**Comment by KochetovNicolai** [comment] 2018-11-29 12:39
Could you show your query, table structure, or create a simple test which can reproduce a problem?

**Comment by wuyanxing001** [comment] 2018-11-30 02:02
version:
ClickHouse client version 18.14.13.
Connecting to localhost:9000.
Connected to ClickHouse server version 18.14.13 revision 54409.

i use DBeaver , SQL like this 
	SELECT
		 *
	FROM
		( SELECT
			SFZ18, JYAQ, AJLBXS, AJBH, XM
		FROM
			test_qiankexinxi
		WHERE XM LIKE '%张%'
			OR SFZ18 LIKE '%张%'
			OR AJBH LIKE '%张%' ) aa ALL
	LEFT JOIN ( SELECT
			CK_XINGMING, CK_GONGMSFHM, CK_ZHIYE, CK_ZHUZHI
		FROM
			test_changzhurenkou ) bb ON
			aa.SFZ18 = bb.CK_GONGMSFHM

table structure:

DESCRIBE TABLE test_qiankexinxi

┌─name───────┬─type───┬─default_type─┬─default_expression─┐
│ id         │ String │              │                    │
│ RYBH       │ String │              │                    │
│ XM         │ String │              │                    │
│ MZ         │ String │              │                    │
│ AJBH       │ String │              │                    │
│ JYAQ       │ String │              │                    │
│ CJDW       │ String │              │                    │
│ AJLBXS     │ String │              │                    │
│ SFZ18      │ String │              │                    │
│ SFZ        │ String │              │                    │
│ CREATEDATE │ Date   │              │                    │
└────────────┴────────┴──────────────┴────────────────────┘

DESCRIBE TABLE test_changzhurenkou

┌─name──────────────┬─type───┬─default_type─┬─default_expression─┐
│ id                │ String │              │                    │
│ CK_GONGMSFHM      │ String │              │                    │
│ CK_XINGMING       │ String │              │                    │
│ CK_XINGMINGPINYIN │ String │              │                    │
│ CK_XUEXING_NV     │ String │              │                    │
│ CK_YUHZGX_NV      │ String │              │                    │
│ CK_ZHIYE          │ String │              │                    │
│ CK_ZHUZHI         │ String │              │                    │
│ CK_SSXQMC         │ String │              │                    │
│ CREATEDATE        │ Date   │              │                    │
└───────────────────┴────────┴──────────────┴────────────────────┘

**Comment by alexey-milovidov** [comment] 2019-01-27 16:41
Duplicate of https://github.com/yandex/ClickHouse/issues/4108

**Comment by 4ertus2** [comment] 2019-02-01 12:39
fixed in master

**Closed by 4ertus2** 2019-02-01 12:39 UTC
Labels: need info
