### ISSUE TITLE
CREATE VIEW IF NOT EXISTS does not work 

### ISSUE THREAD

**Issue by tsionyx** [yandex/ClickHouse#1018] opened 2017-07-24 09:29 UTC
after upgrading server to version 1.1.54245, the `CREATE VIEW IF NOT EXISTS` does not work anymore

```
$ clickhouse-client 
ClickHouse client version 1.1.54236.
Connecting to localhost:9000.
Connected to ClickHouse server version 1.1.54236.

:) CREATE VIEW IF NOT EXISTS foo AS SELECT 1

CREATE VIEW IF NOT EXISTS foo AS
SELECT 1

Ok.

0 rows in set. Elapsed: 0.010 sec. 

:) Bye.

$ clickhouse-client --host 192.168.40.244 
ClickHouse client version 1.1.54236.
Connecting to 192.168.40.244:9000.
Connected to ClickHouse server version 1.1.54245.

:) CREATE VIEW IF NOT EXISTS foo AS SELECT 1

CREATE VIEW IF NOT EXISTS foo AS
SELECT 1

Received exception from server:
Code: 62. DB::Exception: Received from 192.168.40.244:9000. DB::Exception: Syntax error: failed at position 26:  foo AS SELECT 1, expected identifier. 

0 rows in set. Elapsed: 0.265 sec. 
```

**Comment by ztlpn** [comment] 2017-07-24 09:43
Duplicate of #934 
It was fixed in #939

**Closed by ztlpn** 2017-07-24 09:43 UTC
