### ISSUE TITLE
Cannot insert empty value to Int/Float column FROM CSV/TabSeparated

### ISSUE THREAD

**Issue by jaykelin** [yandex/ClickHouse#1832] opened 2018-01-29 11:26 UTC
Clickhouse version:1.1.54342
step 1 , creaate table :
```sql
create table test_local.t_lzj_54342_vertest (dt Date, name String, v1 Int8, v2 Int32, v3 Int64, v4 Float32, v5 String, v6 Int16) engine = MergeTree(dt, (dt, name), 8192);
```
step2, create data file : t_lzj_54342_vertest_CSV.dat
```
2018-01-01,JK,,,3,4,,6
2018-01-01,kk,1,2,,,,
```
step 3, insert into table : 
```shell
cat t_lzj_54342_vertest_CSV.dat | POST 'http://localhost:8123/?query=insert+into+test_local.t_lzj_54342_vertest+Format+CSV'
```
throw exception : 
```
Code: 72, e.displayText() = DB::Exception: Cannot read floating point value: (at row 2)

Row 1:
Column 0,   name: dt,   type: Date,    parsed text: "2018-01-01"
Column 1,   name: name, type: String,  parsed text: "JK"
Column 2,   name: v1,   type: Int8,    ERROR: text ",,3,4,,6<LINE FEED>2" is not like Int8
, e.what() = DB::Exception

```

**Comment by ztlpn** [comment] 2018-02-12 15:59
This is related to the new parsing code for floats introduced in #1665 (note that empty strings for Int columns should still work). The [documentation](https://clickhouse.yandex/docs/en/formats/tabseparated.html) states that parsing of empty strings is implementation-specific, but in this case we probably should just revert to the old behavior and parse them as zero values.

**Comment by alexey-milovidov** [comment] 2018-02-22 17:51
Fixed in master.

**Closed by alexey-milovidov** 2018-02-22 17:51 UTC
Labels: backward compatibility, bug

**Comment by petr-larin** [comment] 2023-10-18 00:09
I use the latest Clickhouse Docker image and seem to have this issue with Floats.
My schema:
CREATE DATABASE IF NOT EXISTS hw;

CREATE TABLE IF NOT EXISTS hw.vac
(
  Ids UInt32,
  Employer String,
  Name String,
  Salary Bool,
  From Float32 DEFAULT 0.0,
  To Float32 DEFAULT 0.0,
  Experience String,
  Schedule String,
  Keys String,
  Description String,
  Area String,
  Professional_roles String,
  Specializations String,
  Profarea_names String,
  Published_at DateTime
)
ENGINE = MergeTree()
ORDER BY Ids;

SET input_format_csv_empty_as_default=1;
SET input_format_defaults_for_omitted_fields=1;

Query:
clickhouse-client --input_format_csv_skip_first_lines=1 --input_format_csv_empty_as_default=1 --input_format_defaults_for_omitted_fields=1 -q "insert into hw.vac format CSV" < /docker-entrypoint-initdb.d/IT_vacancies.csv
[IT_vacancies.csv](https://github.com/ClickHouse/ClickHouse/files/12969755/IT_vacancies.csv)

The datafile is just one line.
![Screenshot 2023-10-18 030352](https://github.com/ClickHouse/ClickHouse/assets/113700952/719bb671-c2db-485e-8b48-0b1be645c24f)

**Comment by den-crane** [comment] 2023-10-18 00:25
@petr-larin the problem is in datetime format `2021-12-02 12:15:37+03:00` -- Clickhouse expects `2021-12-02 12:15:37` by default.

see `date_time_input_format` , `--date_time_input_format=best_effort`


```
clickhouse-client --input_format_csv_skip_first_lines=1 --input_format_csv_empty_as_default=1 --input_format_defaults_for_omitted_fields=1 --date_time_input_format=best_effort -q "insert into hw.vac format CSV" < IT_vacancies.csv

SELECT *
FROM hw.vac

Query id: f01d3d30-dc4e-425e-8eb6-90a931433db9

┌──────Ids─┬─Employer─┬─Name───────────────────┬─Salary─┬───From─┬─To─┬─Experience─┬─Schedule─┬─Keys───────────────────────────────────┬─Description─┬─Area─┬─Professional_roles─┬─Specializations─┬─Profarea_names─┬────────Published_at─┐
│ 49313809 │ Space307 │ Golang Developer (abc) │ true   │ 251322 │  0 │ abc        │ abc      │ ['Docker', 'Golang', 'Redis', 'Kafka'] │ abc         │ bc   │ ccc                │ ccc             │ ccc            │ 2021-12-02 09:15:37 │
└──────────┴──────────┴────────────────────────┴────────┴────────┴────┴────────────┴──────────┴────────────────────────────────────────┴─────────────┴──────┴────────────────────┴─────────────────┴────────────────┴─────────────────────┘
```

**Comment by petr-larin** [comment] 2023-10-18 01:15
@den-crane: it worked, many thanks ))))
