### ISSUE TITLE
Test 00107 crashes the server

### ISSUE THREAD

**Issue by mfridental** [yandex/ClickHouse#999] opened 2017-07-18 20:39 UTC
I've pinned down the difference in my system crashing the server at the test 00107 while passing the test in the clean installation.

Please add this as the first line to the test:
SET max_bytes_before_external_group_by=10000000;

This should crash the server.

**Comment by alexey-milovidov** [comment] 2017-07-18 20:42
Thanks! We just have tracked down this issue.
And it is fixed here: https://github.com/yandex/ClickHouse/pull/998

**Comment by ztlpn** [comment] 2017-07-19 19:48
Easily reproducible, thanks! Will fix.

**Comment by mfridental** [comment] 2017-07-19 20:45
Confirming that fix for #998 also fixes this issue. Thanks!

**Comment by ztlpn** [comment] 2017-07-19 22:40
@mfridental are you sure? Because I still can reproduce it.

**Comment by mfridental** [comment] 2017-07-20 18:11
You're right, the issue is still there

**Comment by ztlpn** [comment] 2017-08-21 12:55
Fixed in 1.1.54276.

**Closed by ztlpn** 2017-08-21 12:55 UTC
Labels: bug
