### ISSUE TITLE
Segmentation fault due to SUM in join-query

### ISSUE THREAD

**Issue by grigory51** [yandex/ClickHouse#3478] opened 2018-10-27 09:44 UTC
OS: macOS 10.14
Version: docker, yandex/clickhouse-server latest a55b5216b0d9 (18.14.10)
DDL:
```sql
CREATE TABLE IF NOT EXISTS hits (
  uuid         String,
  time         DateTime,
  project      String,
  host         String,
  path         String,
  utm_source   String,
  utm_medium   String,
  utm_campaign String,
  utm_content  String,
  utm_term     String,
  visit_id     String,
  user_id      String
)
  ENGINE = ReplacingMergeTree()
    ORDER BY (time, uuid);

CREATE TABLE IF NOT EXISTS expenses (
  utm_source   String,
  utm_medium   String,
  utm_campaign String,
  utm_content  String,
  utm_term     String,
  time         DateTime,
  amount       Decimal64(4)
)
ENGINE = ReplacingMergeTree()
ORDER BY (utm_source, utm_medium, utm_campaign, utm_content, utm_term, time);
```

Query:
```sql
SELECT utm_source,
       utm_campaign,
       utm_content,
       utm_medium,
       utm_term,
       count(*)           as count,
       toStartOfDay(time) as group_time,
       Amount
FROM hits any
       LEFT JOIN (
    select utm_source,
           utm_campaign,
           utm_content,
           utm_medium,
           utm_term,
           sum(amount)             as Amount,
           toStartOfDay(time) as group_time
    from expenses
    group by utm_source, utm_campaign, utm_content, utm_medium, utm_term, amount, group_time
    ) using utm_source, utm_campaign, utm_content, utm_medium, utm_term, group_time
WHERE (
          (
              (utm_source != 'NULL' and utm_source != '') OR
              (utm_campaign != 'NULL' and utm_campaign != '') OR
              (utm_content != 'NULL' and utm_content != '') OR
              (utm_medium != 'NULL' and utm_medium != '') OR
              (utm_term != 'NULL' and utm_term != '')
              ) AND
          '2018-09-20 00:00:00' <= time AND
          time < '2018-09-22 00:00:00' AND
          utm_source IN ('telegram') AND
          utm_campaign IN ('linux') AND
          utm_content IN ('welcome_paypost') AND
          1 = 1 AND
          1 = 1
          )
GROUP BY utm_source, utm_campaign, utm_content, utm_medium, utm_term, Amount, group_time
ORDER BY utm_source, utm_campaign, utm_content, utm_medium, utm_term, group_time
LIMIT 0, 500;
```

If i will replace `sum(amount) as Amount` to `amount as Amount`, query will successfully executed

**Comment by alesapin** [comment] 2018-10-29 12:31
Maybe you can provide server logs and/or some data to reproduce the problem? On empty it doesn't reproduce.

**Comment by grigory51** [comment] 2018-10-30 07:46
Sorry, i try again and everything okey.
Found this logs in clickhouse-server.err.log

```
2018.10.27 09:38:08.384072 [ 2 ] {} <Error> BaseDaemon: ########################################
2018.10.27 09:38:08.384147 [ 2 ] {} <Error> BaseDaemon: (from thread 23) Received signal Segmentation fault (11).
2018.10.27 09:38:08.384186 [ 2 ] {} <Error> BaseDaemon: Address: NULL pointer.
2018.10.27 09:38:08.384218 [ 2 ] {} <Error> BaseDaemon: Access: read.
2018.10.27 09:38:08.384249 [ 2 ] {} <Error> BaseDaemon: Unknown si_code.
2018.10.27 09:38:08.456515 [ 2 ] {} <Error> BaseDaemon: 0. /usr/bin/clickhouse-server(DB::ColumnDecimal<DB::Decimal<__int128> >::deserializeAndInsertFromArena(char const*)+0x16) [0x76be9c6]
2018.10.27 09:38:08.456703 [ 2 ] {} <Error> BaseDaemon: 1. /usr/bin/clickhouse-server(void DB::Aggregator::convertToBlockImplFinal<DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, HashTableGrower<8ul>, Allocator<true> > >, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, HashTableGrower<8ul>, Allocator<true> > >(DB::AggregationMethodSerialized<HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, HashTableGrower<8ul>, Allocator<true> > >&, HashMapTable<StringRef, HashMapCellWithSavedHash<StringRef, char*, DefaultHash<StringRef>, HashTableNoState>, DefaultHash<StringRef>, HashTableGrower<8ul>, Allocator<true> >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&, std::vector<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn>, std::allocator<COWPtr<DB::IColumn>::mutable_ptr<DB::IColumn> > >&) const+0x74) [0x7a5f1b4]
2018.10.27 09:38:08.456770 [ 2 ] {} <Error> BaseDaemon: 2. /usr/bin/clickhouse-server() [0x7a3e6c8]
2018.10.27 09:38:08.456821 [ 2 ] {} <Error> BaseDaemon: 3. /usr/bin/clickhouse-server(DB::Aggregator::prepareBlockAndFillSingleLevel(DB::AggregatedDataVariants&, bool) const+0x68) [0x7a3f4d8]
2018.10.27 09:38:08.456870 [ 2 ] {} <Error> BaseDaemon: 4. /usr/bin/clickhouse-server(DB::MergingAndConvertingBlockInputStream::readImpl()+0x44c) [0x7aef7cc]
2018.10.27 09:38:08.456927 [ 2 ] {} <Error> BaseDaemon: 5. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.456975 [ 2 ] {} <Error> BaseDaemon: 6. /usr/bin/clickhouse-server(DB::ParallelAggregatingBlockInputStream::readImpl()+0x4eb) [0x79e93ab]
2018.10.27 09:38:08.457020 [ 2 ] {} <Error> BaseDaemon: 7. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457067 [ 2 ] {} <Error> BaseDaemon: 8. /usr/bin/clickhouse-server(DB::CreatingSetsBlockInputStream::readImpl()+0xda) [0x799bdba]
2018.10.27 09:38:08.457112 [ 2 ] {} <Error> BaseDaemon: 9. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457158 [ 2 ] {} <Error> BaseDaemon: 10. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2e) [0x79b2b7e]
2018.10.27 09:38:08.457204 [ 2 ] {} <Error> BaseDaemon: 11. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457250 [ 2 ] {} <Error> BaseDaemon: 12. /usr/bin/clickhouse-server(DB::PartialSortingBlockInputStream::readImpl()+0x2e) [0x79ee1ae]
2018.10.27 09:38:08.457295 [ 2 ] {} <Error> BaseDaemon: 13. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457341 [ 2 ] {} <Error> BaseDaemon: 14. /usr/bin/clickhouse-server(DB::MergeSortingBlockInputStream::readImpl()+0x3d5) [0x79cbcf5]
2018.10.27 09:38:08.457411 [ 2 ] {} <Error> BaseDaemon: 15. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457457 [ 2 ] {} <Error> BaseDaemon: 16. /usr/bin/clickhouse-server(DB::ExpressionBlockInputStream::readImpl()+0x2e) [0x79b2b7e]
2018.10.27 09:38:08.457503 [ 2 ] {} <Error> BaseDaemon: 17. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457548 [ 2 ] {} <Error> BaseDaemon: 18. /usr/bin/clickhouse-server(DB::LimitBlockInputStream::readImpl()+0x225) [0x6addb05]
2018.10.27 09:38:08.457593 [ 2 ] {} <Error> BaseDaemon: 19. /usr/bin/clickhouse-server(DB::IProfilingBlockInputStream::read()+0x25a) [0x6ad979a]
2018.10.27 09:38:08.457641 [ 2 ] {} <Error> BaseDaemon: 20. /usr/bin/clickhouse-server(DB::copyData(DB::IBlockInputStream&, DB::IBlockOutputStream&, std::atomic<bool>*)+0x81) [0x6af4181]
2018.10.27 09:38:08.457704 [ 2 ] {} <Error> BaseDaemon: 21. /usr/bin/clickhouse-server(DB::executeQuery(DB::ReadBuffer&, DB::WriteBuffer&, bool, DB::Context&, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>)+0x56b) [0x7691e3b]
2018.10.27 09:38:08.457766 [ 2 ] {} <Error> BaseDaemon: 22. /usr/bin/clickhouse-server(DB::HTTPHandler::processQuery(Poco::Net::HTTPServerRequest&, HTMLForm&, Poco::Net::HTTPServerResponse&, DB::HTTPHandler::Output&)+0x3169) [0x30a2579]
2018.10.27 09:38:08.457813 [ 2 ] {} <Error> BaseDaemon: 23. /usr/bin/clickhouse-server(DB::HTTPHandler::handleRequest(Poco::Net::HTTPServerRequest&, Poco::Net::HTTPServerResponse&)+0x3be) [0x30a4b9e]
2018.10.27 09:38:08.457887 [ 2 ] {} <Error> BaseDaemon: 24. /usr/bin/clickhouse-server(Poco::Net::HTTPServerConnection::run()+0x332) [0x9b6f4d2]
2018.10.27 09:38:08.457951 [ 2 ] {} <Error> BaseDaemon: 25. /usr/bin/clickhouse-server(Poco::Net::TCPServerConnection::start()+0xf) [0x9b67d7f]
2018.10.27 09:38:08.457998 [ 2 ] {} <Error> BaseDaemon: 26. /usr/bin/clickhouse-server(Poco::Net::TCPServerDispatcher::run()+0x16a) [0x9b6815a]
2018.10.27 09:38:08.458044 [ 2 ] {} <Error> BaseDaemon: 27. /usr/bin/clickhouse-server(Poco::PooledThread::run()+0x77) [0x9c84f37]
2018.10.27 09:38:08.458096 [ 2 ] {} <Error> BaseDaemon: 28. /usr/bin/clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x38) [0x9c80aa8]
2018.10.27 09:38:08.458139 [ 2 ] {} <Error> BaseDaemon: 29. /usr/bin/clickhouse-server() [0xa3da90f]
2018.10.27 09:38:08.458182 [ 2 ] {} <Error> BaseDaemon: 30. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f46f5d9f6db]
```

**Comment by 4ertus2** [comment] 2018-10-30 12:05
There was analogous crash in another part of Aggregator. The reason was aligned instructions in gcc release build with unaligned data in Aggregator.

**Comment by alexey-milovidov** [comment] 2018-12-28 20:47
Fixed in recent releases.

**Closed by alexey-milovidov** 2018-12-28 20:47 UTC
