### ISSUE TITLE
where in (subquery) results in an empty result set

### ISSUE THREAD

**Issue by Girgitt** [yandex/ClickHouse#2623] opened 2018-07-10 13:29 UTC
Did anyone experience a behavior where if WHERE IN is applied to a simple subquery an empty set is returned?

ClickHouse client version 1.1.54362.
Connecting to 127.0.0.1:9000.
Connected to ClickHouse server version 1.1.54362.

:) select ts,val from analog_archives where ids in (116) limit 10;

SELECT
    ts,
    val
FROM analog_archives
WHERE ids IN 116
LIMIT 10

┌─────────ts─┬───────val─┐
│ 1432087323 │ -0.246795 │
│ 1432087334 │ -0.221154 │
│ 1432087335 │ -0.230769 │
│ 1432087347 │ -0.230769 │
│ 1432087348 │ -0.224359 │
│ 1432087474 │ -0.211538 │
│ 1432087519 │ -0.224359 │
│ 1432087520 │ -0.233974 │
│ 1432088100 │ -0.198718 │
│ 1432088681 │  -0.25641 │
└────────────┴───────────┘

10 rows in set. Elapsed: 0.103 sec. Processed 65.54 thousand rows, 786.43 KB (636.61 thousand rows/s., 7.64 MB/s.)

:) select ts,val from analog_archives where ids in (select 116) limit 10;

SELECT
    ts,
    val
FROM analog_archives
WHERE ids IN
(
    SELECT 116
)
LIMIT 10

Ok.

0 rows in set. Elapsed: 0.321 sec.

**Comment by filimonov** [comment] 2018-07-10 14:02
There was few issues with IN, and may by that case was already fixed in last versions. 

But I can't reproduce even on same version.

With `WHERE ids IN ( SELECT 116 )` i get an exception about incompatible types, so i need to do typecast manually. 

```
:) create table test Engine=MergeTree ORDER BY number as SELECT number FROM numbers(200);
Ok.
0 rows in set. Elapsed: 0.082 sec. 

:) INSERT INTO test SELECT number FROM numbers(200);
Ok.
0 rows in set. Elapsed: 0.003 sec. 

:) INSERT INTO test SELECT number FROM numbers(200);
Ok.
0 rows in set. Elapsed: 0.003 sec. 

:) INSERT INTO test SELECT number FROM numbers(200);
Ok.
0 rows in set. Elapsed: 0.003 sec. 


:) select * from test where number in (116);

SELECT *
FROM test 
WHERE number IN 116

┌─number─┐
│    116 │
└────────┘
┌─number─┐
│    116 │
└────────┘
┌─number─┐
│    116 │
└────────┘
┌─number─┐
│    116 │
└────────┘

4 rows in set. Elapsed: 0.003 sec. 

:) select * from test where number in (select 116);

SELECT *
FROM test 
WHERE number IN 
(
    SELECT 116
)

Received exception from server (version 1.1.54362):
Code: 53. DB::Exception: Received from localhost:9000, ::1. DB::Exception: Types of column 1 in section IN don't match: UInt8 on the right, UInt64 on the left.. 

0 rows in set. Elapsed: 0.042 sec. 

:) select * from test where number in (select toUInt64(116));

SELECT *
FROM test 
WHERE number IN 
(
    SELECT toUInt64(116)
)

┌─number─┐
│    116 │
└────────┘
┌─number─┐
│    116 │
└────────┘
┌─number─┐
│    116 │
└────────┘
┌─number─┐
│    116 │
└────────┘

4 rows in set. Elapsed: 0.001 sec. 
```
Can you check if problem still exists on newest version? If it exists - please show you create table / help to create reproducible test case.

**Comment by blinkov** [comment] 2018-10-15 16:19
The requested information has not been provided.

**Closed by blinkov** 2018-10-15 16:19 UTC
Labels: need info
