### ISSUE TITLE
Users cannot be supplied just from zookeeper

### ISSUE THREAD

**Issue by bobrik** [yandex/ClickHouse#856] opened 2017-06-07 04:32 UTC
I want to keep all more or less dynamic configuration (users, shards) in zookeeper. So I started with users:

```xml
<users from_zk="/clickhouse/dev/config-overrides/users" />
```

In zookeeper I have:

```
[zk: localhost:2181(CONNECTED) 15] get /clickhouse/dev/config-overrides/users
```

```xml
<ivan>
  <networks incl="networks" replace="replace">
    <ip>::/0</ip>
  </networks>
  <password_sha256_hex>f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7</password_sha256_hex>
  <profile>default</profile>
  <quota>default</quota>
</ivan>
```

```xml
	<users><ivan>
  <networks incl="networks" replace="replace">
    <ip>::/0</ip>
  </networks>
  <password_sha256_hex>f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7</password_sha256_hex>
  <profile>default</profile>
  <quota>default</quota>
</ivan></users>
```

In `/etc/clickhouse-server/config-preprocessed.xml` this renders as:

```xml
	<users><ivan>
  <networks incl="networks" replace="replace">
    <ip>::/0</ip>
  </networks>
  <password_sha256_hex>f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7</password_sha256_hex>
  <profile>default</profile>
  <quota>default</quota>
</ivan></users>
```

This seems correct, but for some reason doesn't work (user is not found):

```
$ clickhouse-client --host clickhouse1 --user ivan --password hunter2
ClickHouse client version 1.1.54236.
Connecting to database system at clickhouse1:9000 as user ivan.
Code: 192. DB::Exception: Received from clickhouse1:9000, 172.21.0.5. DB::Exception: Unknown user ivan.
```

However, I managed to get individual users work by having this:

```xml
	<users>
		<ivan from_zk="/clickhouse/dev/config-overrides/ivan" />
	</users>
```

```
[zk: localhost:2181(CONNECTED) 16] get /clickhouse/dev/config-overrides/ivan
```

```xml
<networks incl="networks" replace="replace">
  <ip>::/0</ip>
</networks>
<password_sha256_hex>f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7</password_sha256_hex>
<profile>default</profile>
<quota>default</quota>
```

In `/etc/clickhouse-server/config-preprocessed.xml` this renders as:

```xml
	<users>
		<ivan><networks incl="networks" replace="replace">
  <ip>::/0</ip>
</networks>
<password_sha256_hex>f52fbd32b2b3b86ff88ef6c490628285f482af15ddcb29541f94bcf526a3f6c7</password_sha256_hex>
<profile>default</profile>
<quota>default</quota></ivan>
	</users>
```

And it works:

```
$ clickhouse-client --host clickhouse1 --user ivan --password hunter2
ClickHouse client version 1.1.54236.
Connecting to database system at clickhouse1:9000 as user ivan.
Connected to ClickHouse server version 1.1.54236.

:)
```

So in both cases I have the same rendered config, but in the first case user is not found. This is quite sad, given that the most frequent operation is adding and removing users and the second case doesn't cover that.

Is there a way to make it work?

**Comment by bobrik** [comment] 2017-06-07 20:51
When I have individual users in zk and update them:

```
2017.06.07 20:48:19.225584 [ 11 ] <Debug> ConfigReloader: Loading config `/etc/clickhouse-server/config.xml'
2017.06.07 20:48:19.225584 [ 17 ] <Debug> ConfigReloader: Loading config `/etc/clickhouse-server/users.xml'
```

When I have whole `<users>` in zk and update it:

```
2017.06.07 20:50:19.457473 [ 11 ] <Debug> ConfigReloader: Loading config `/etc/clickhouse-server/config.xml'
```

**Comment by bobrik** [comment] 2017-06-07 21:19
With the help from @vavrusa we figured out that `replace="replace"` was missing. This works:

```xml
<?xml version="1.0"?>
<yandex>
	<profiles from_zk="/clickhouse-overrides/dev/profiles" replace="replace" />
	<quotas from_zk="/clickhouse-overrides/dev/quotas" replace="replace" />
	<users from_zk="/clickhouse-overrides/dev/users" replace="replace" />
</yandex>
```

**Comment by ztlpn** [comment] 2017-06-08 17:56
Hi Ivan!

Glad you managed to get this working.

Did you add your overrides as a file in the `conf.d` directory? If yes, here is what happened. Users configuration is actually loaded not from `config.xml`, but from `users.xml` which is a separate config. First, overrides from your file were merged into that config. As `users.xml` already contains the `<users>` tag, in the absence of `replace` attribute the `from_zk` attribute was lost during this process, so your configuration was never added.

Now, here is why you were unable to debug the issue: files from the `conf.d` directory are added to _both_ configs (in contrast to files from `config.d` and `users.d` which are added only to their respective configs). So your users configuration was inserted without problems into `config-preprocessed.xml` (where it didn't affect anything), but if you looked at the `users-preprocessed.xml` you would see the difference.

Finally, the most interesting question - what to do with this :) The root of the problem is that first the override files were merged into the main file, and only then includes were processed. Let me think a bit on whether reversing this order is more sensible.

**Comment by wayhome** [comment] 2018-01-31 07:42
I  had the similar problem with the config of Graphite.

In zookeeper I have:

```
(CONNECTED) /> get /clickhouse/config-overrides/graphite

<host>carbon-relay</host>
<port>24000</port>
<timeout>0.1</timeout>
<interval>5</interval>
<root_path>adclickhouse</root_path>
<metrics>true</metrics>
<events>true</events>
<asynchronous_metrics>true</asynchronous_metrics>
```

I  config.xml I have:

```
    <graphite from_zk="/clickhouse/config-overrides/graphite"/>
```

And `/etc/clickhouse-server/config-preprocessed.xml`  this renders as:

```
    <graphite>
<host>carbon-relay</host>
<port>24000</port>
<timeout>0.1</timeout>
<interval>5</interval>
<root_path>adclickhouse</root_path>
<metrics>true</metrics>
<events>true</events>
<asynchronous_metrics>true</asynchronous_metrics>
</graphite>
```

Then I restart the clickhouse, and the `/var/log/clickhouse-server/clickhouse-server.err.log` has:

```
<Warning> Application: Fail to write to Graphite localhost:42000. e.what() = Connection refused, e.message() = 127.0.0.1:42000
```

**Comment by blinkov** [comment] 2018-09-13 10:34
@bobrik do you have any further questions?

**Closed** 2018-09-13 16:41 UTC
Labels: need info
