### ISSUE TITLE
Segmentation fault when you alter a table to add a Nullable field

### ISSUE THREAD

**Issue by silviucpp** [yandex/ClickHouse#875] opened 2017-06-14 15:07 UTC
Hello,

```sql
create table test.funnel (EventDate Date, a Nullable(UInt8)) ENGINE = MergeTree(EventDate, (EventDate), 8192);

//insert some datas

alter table test.funnel ADD COLUMN b Nullable(String));
select * from test.funnel format JSON
```
I'm getting:

```
2017.06.14 14:58:40.147539 [ 5 ] <Information> executeQuery: Read 3 rows, 12.00 B in 0.001 sec., 4490 rows/sec., 17.54 KiB/sec.
2017.06.14 14:58:40.147715 [ 5 ] <Information> HTTPHandler: Done processing query
2017.06.14 14:59:14.659618 [ 6 ] <Information> HTTPHandler: Done processing query
2017.06.14 15:01:26.863319 [ 29 ] <Error> BaseDaemon: ########################################
2017.06.14 15:01:26.863399 [ 29 ] <Error> BaseDaemon: (from thread 5) Received signal Segmentation fault (11).
2017.06.14 15:01:26.863419 [ 29 ] <Error> BaseDaemon: Address: NULL pointer.
2017.06.14 15:01:26.868782 [ 29 ] <Error> BaseDaemon: 1. clickhouse-server(DB::ColumnNullable::ColumnNullable(std::shared_ptr<DB::IColumn>, std::shared_ptr<DB::IColumn>)+0x64) [0x293de44]
2017.06.14 15:01:26.868832 [ 29 ] <Error> BaseDaemon: 2. clickhouse-server(Poco::ThreadImpl::runnableEntry(void*)+0x96) [0x32de156]
2017.06.14 15:01:26.868858 [ 29 ] <Error> BaseDaemon: 3. /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7fbee8621184]
2017.06.14 15:01:26.868898 [ 29 ] <Error> BaseDaemon: 4. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fbee7c3cbed]
```

**Comment by ztlpn** [comment] 2017-06-16 19:58
I've tried to reproduce with the following script:
```sql
create table test.funnel (EventDate Date, a Nullable(UInt8)) ENGINE = MergeTree(EventDate, (EventDate), 8192);
insert into test.funnel values ('2017-06-16', 1);
alter table test.funnel ADD COLUMN b Nullable(String);
select * from test.funnel format JSON;
```
but it works as expected. Can you provide a sample of data which causes the segfault?

**Comment by silviucpp** [comment] 2017-06-16 20:54
I will do this on monday and provide you steps. I'm testing on last stable by the way

Silviu

**Comment by silviucpp** [comment] 2017-06-20 13:02
Hello,

I'm using the last stable v1.1.54236-stable and I can replicate this with the steps provided by you. 
Do you have any idea on how I can add the testing versions on ubuntu distribution ?

Silviu

**Comment by ztlpn** [comment] 2017-06-20 17:52
Turns out the bug is indeed present in 1.1.54236, but is fixed in master: https://github.com/yandex/ClickHouse/commit/8343cf3578c7818a5123f35d3ed3580cae3a99c8 Thanks, Silviu!

Regarding testing tags - we don't publish packages for these tags because the code can be unstable. We hope to publish the new release soon - stay tuned.

**Closed by ztlpn** 2017-06-20 17:52 UTC

**Comment by silviucpp** [comment] 2017-06-20 20:03
Thanks a lot
