### ISSUE TITLE
Bug docker:  No such file or directory: "/usr/share/zoneinfo/"

### ISSUE THREAD

**Issue by vvp83** [yandex/ClickHouse#789] opened 2017-05-15 08:21 UTC
cat /etc/issue
Debian GNU/Linux 8 \n \l
sudo dpkg-reconfigure tzdata

root@Debian-87-jessie-64-minimal ~ # ls -la /usr/share/zoneinfo/
total 280
drwxr-xr-x 21 root root  4096 Mar 29 13:12 .
drwxr-xr-x 87 root root  4096 May 15 09:38 ..
drwxr-xr-x  2 root root  4096 Mar 29 13:12 Africa
drwxr-xr-x  6 root root  4096 Mar 29 13:12 America

root@Debian-87-jessie-64-minimal ~ # docker pull yandex/clickhouse-server
Using default tag: latest
latest: Pulling from yandex/clickhouse-server

Digest: sha256:0932b128a79447a92d56610869987ecb42288e5eed85d94b3d7d7e477c08a54a

docker create --name clickhouse-server yandex/clickhouse-server
docker start clickhouse-server
 docker logs -f clickhouse-server
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
POCO ERROR: Exception: Could not determine local time zone: boost::filesystem::canonical: No such file or directory: "/usr/share/zoneinfo/"
terminate called after throwing an instance of 'Poco::Exception'
  what():  Exception

Checked at old version 1.1.54181  it started

**Comment by ztlpn** [comment] 2017-05-15 10:05
Caused by: https://bugs.launchpad.net/cloud-images/+bug/1682622

**Comment by zloidemon** [comment] 2017-05-15 13:55
https://github.com/yandex/ClickHouse/pull/791

**Comment by ztlpn** [comment] 2017-05-16 18:46
We've pushed fixed images to docker hub under the `latest` tag. @zloidemon Thanks for the PR!

**Closed by ztlpn** 2017-05-16 18:46 UTC
