### ISSUE TITLE
Problem with Add Colum in ReplicatedMergeTree

### ISSUE THREAD

**Issue by perez1987** [yandex/ClickHouse#2595] opened 2018-07-05 11:22 UTC
We are trying to add a column with a default value.

In the tables with MergeTree we have executed the following command:
ALTER TABLE BBDD.Table_Rep ADD COLUMN Field2 DEFAULT lower (splitByChar ('\\', Field1) [length (splitByChar ('\\', Field1))]) AFTER Field1;

It runs OK.

However, when we try the same in tables with ReplicatedMergeTree.

ALTER TABLE BBDD.Table2_Rep ADD COLUMN Field2 DEFAULT lower (splitByChar ('\\', Field1) [length (splitByChar ('\\', Field1))]) AFTER Field1;

After 60 seconds:
Alter is not finished because timeout when waiting for some replicas: node4 (replication_alter_columns_timeout = 60). Alter will be done asynchronously

It seems that everything has gone OK, it does not give us any error.

If we go to the log:
2018.07.05 11: 04: 51.062796 [1444] <Error> executeQuery: Code: 341, e.displayText () = DB :: Exception: Alter is not finished because timeout when waiting for some replicas: node4 (replication_alter_columns_timeout = 60). Alter will be done asynchronously., E.what () = DB :: Exception (from [:: 1]: 52892) (in query: ALTER TABLE MSSP.Table_Rep ADD COLUMN Field2 DEFAULT lower (splitByChar ('\\', Field1 ) [length (splitByChar ('\\', Field1))]) AFTER Field1, Stack trace:

2018.07.05 11: 04: 52.193662 [129] <Error> BBDD.Table (StorageReplicatedMergeTree, AlterThread): void DB :: ReplicatedMergeTreeAlterThread :: run (): Code: 62, e.displayText () = DB :: Exception: Syntax error (default expression): failed at position 51: \ ', Field1))]). Unrecognized token, e.what () = DB :: Exception, Stack trace:

0. / usr / bin / clickhouse-server (StackTrace :: StackTrace () + 0x15) [0x84eb125]
1. / usr / bin / clickhouse-server (DB :: Exception :: Exception (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, int) + 0x21) [0x2ccbf01]
2. / usr / bin / clickhouse-server (DB :: parseQuery (DB :: IParser &, char const *, char const *, std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, unsigned long) + 0xab) [0x84b3e5b]
3. / usr / bin / clickhouse-server (DB :: ColumnsDescription :: parse (std :: __cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &) + 0x61e) [0x7df52ce]
4. / usr / bin / clickhouse-server (DB :: ReplicatedMergeTreeAlterThread :: run () + 0x276) [0x8205b26]
5. / usr / bin / clickhouse-server () [0x8dd3a8e]
6. /lib/x86_64-linux-gnu/libpthread.so.0(+0x76b9) [0x7f6b8fc126b9]
7. /lib/x86_64-linux-gnu/libc.so.6(clone+0x6c) [0x7f6b8f43b41c]

We see this syntax error. Why?

We go to the ZK and see the table that is trying to create:

(CONNECTED [node4]) / clickhouse / tlevents / tables / Table / 4> json_cat columns
columns format version: 1
42 columns:
.......
........
.......
`Field2` String DEFAULT lower (splitByChar ('\\\\', Field1) [length (splitByChar ('\\\\', Field1))])
.......
........
.......

The table stops being accessible because it is not able to create it.

What is the problem?
Why in a MergeTree if that works?
What syntax error is there that causes it to fail in Replication, specifically StorageReplicatedMergeTree?
Can there be a bug?

Thank you

**Comment by filimonov** [comment] 2018-07-05 14:02
Hmmm... Should be checked. May be some improper escaping/deescaping of backslash when reading / writing alter to a zookeeper.

Possible workaround: try to use unhex('5C') as your split char (it's ascii code of backslash char). 

And by the way: you can access last element of the array using negative index. 

```
SELECT [1, 2, 3, 4, 5, 6, 7][-1]; -- 7 
SELECT [1, 2, 3, 4, 5, 6, 7][-2]; -- 6 
-- etc.
```

I.e. as a workaround try to do it like that: 
```ALTER TABLE BBDD.Table2_Rep ADD COLUMN Field2 DEFAULT lower(splitByChar (unhex('5C'), Field1) [-1]) AFTER Field1;```

**Comment by perez1987** [comment] 2018-07-05 14:52
@filimonov Works! But there is a problem with character escaping when a field with a default value is inserted into tables with ReplicatedMergeTree. Or not?

**Comment by filimonov** [comment] 2018-07-05 15:28
> But there is a problem with character escaping ... Or not?

Reproducable test should be created to answer that question. May be it's a bug.

**Comment by perez1987** [comment] 2018-07-06 07:03
@filimonov  thank you.

We have tested it and we can not create it with the command I said in my first comment. With your workaround, it works. I think it's a bug when creating a column in tables of the Replicated type

**Comment by filimonov** [comment] 2018-07-06 15:33
>  I think it's a bug when creating a column in tables of the Replicated type

Please give some details to help debug it:
1) version of Clickhouse used.
2) exact failing query. The query you've provided is not correct. It can't be parsed because of bad backspaces sequence:
```
:) ALTER TABLE Table_Rep ADD COLUMN Field2 DEFAULT lower (splitByChar ('\', Field1 ) [length (splitByChar ('\', Field1))]) AFTER Field1;

Syntax error: failed at position 106:

ALTER TABLE Table_Rep ADD COLUMN Field2 DEFAULT lower (splitByChar ('\', Field1 ) [length (splitByChar ('\', Field1))]) AFTER Field1;

Unrecognized token
```
3) how do you send your query (http / clickhouse client)?

**Comment by perez1987** [comment] 2018-07-16 06:54
Sorry for the delay in answering @filimonov 

Version: 1.1.54385

Exactly query:
ALTER TABLE BBDD.Table ADD COLUMN Filename DEFAULT splitByChar('\\', Path)[ length (splitByChar('\\', Path)) ] AFTER Path

If I execute a select instead of an alter I execute the split without problems.

However, if I execute alter, the query does not give an error, it indicates that:
After 60 seconds:
Alter is not finished because timeout when waiting for some replicas: node4 (replication_alter_columns_timeout = 60). Alter will be done asynchronously

After that, the table is no longer accessible until the task it has queued is canceled.

Why, if it fails, does it fail to execute the alter?
Why the select if it works correctly?

With the query that you sent me, the split works without problems.

I think it's a bug in that version, I do not know exactly where.

**Comment by alexey-milovidov** [comment] 2018-10-14 18:50
There was an issue with proper serialization of expressions in columns definition in ReplicatedMergeTree.

It was present in all versions before 1.1.54387 and was fixed in https://github.com/yandex/ClickHouse/commit/8901414a

It is possible to execute an ALTER query on ReplicatedMergeTree with proper escaping: `splitByChar('\\', Path)`. Then it was serialized incorrectly inside ZooKeeper nodes, but older version still can read deserialize it, in most cases. In newer version, the bug was fixed, but the server cannot deserialize `splitByChar('\', Path)` from old version.

The fix for proper serialization introduced (unavoidable) incompatibility between versions. This can be fixed manually by changing the value of the corresponding node in ZK.

**Closed** 2018-10-14 18:51 UTC
Labels: already fixed, backward compatibility, bug
