### ISSUE TITLE
High memory usage when joined table has many columns (regression)

### ISSUE THREAD

**Issue by bgranvea** [yandex/ClickHouse#5579] opened 2019-06-11 08:56 UTC
Memory usage of a simple join query seems to increase with the number of columns of the joined table, even if these columns are not in result. The problem can be reproduced in versions 19.3 up to 19.7 (19.1 is fine).

Steps to reproduce:

```
create table A (id String, ts DateTime) ENGINE=MergeTree order by tuple();

insert into A select number,now() from system.numbers limit 600;

create table B (id String, ts DateTime, a0 Nullable(Float64), a1 Nullable(Float64), a2 Nullable(Float64), ... (500 columns) ) ENGINE=MergeTree order by tuple();

insert into B select number,now(),1,1,... (500 values) from system.numbers limit 20000000;

select a.id FROM A a LEFT JOIN B b ON a.id=b.id;

Progress: 1.03 million rows, 4.66 GB (226.75 thousand rows/s., 1.02 GB/s.)  5%Received exception from server (version 19.7.3):
Code: 241. DB::Exception: Received from localhost:9000, 127.0.0.1. DB::Exception: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 131072 bytes), maximum: 9.31 GiB: (while reading column a350)
```

Workaround:
`select a.id FROM A a LEFT JOIN (select id FROM B) b ON a.id=b.id;
`

The problem with the workaround is as the request is generated by a BI (Tableau), I cannot easily modify it.

I've seen this issue https://github.com/yandex/ClickHouse/pull/4757 but the flag multiple_joins_omit_unused_columns doesn't exist in version 19.7??

**Comment by filimonov** [comment] 2019-06-11 13:48
Looks like duplicate of https://github.com/yandex/ClickHouse/issues/5190, fixed in https://github.com/yandex/ClickHouse/pull/5194

Please check 19.8.

**Comment by bgranvea** [comment] 2019-06-11 15:40
Is there a docker image of 19.8 somewhere or do I have to build from sources?

**Comment by den-crane** [comment] 2019-06-11 15:48
http://repo.yandex.ru/clickhouse/deb/prestable/main/

cat /etc/apt/sources.list.d/clickhouse.list
deb http://repo.yandex.ru/clickhouse/deb/prestable/ main/

19.8.2.2

Or check http://repo.yandex.ru/clickhouse/deb/testing/
https://github.com/yandex/ClickHouse/releases

**Comment by bgranvea** [comment] 2019-06-12 06:50
Thanks for the help.

This works ok with 19.8.2.2. 

This bug is a showstopper for us. Any chance that this fix is merged into 19.7 and other previous stable branches?

**Comment by filimonov** [comment] 2019-06-12 11:50
@alesapin @proller It's a regression, so probably should be backported?

**Comment by bgranvea** [comment] 2019-06-12 16:00
yes we saw the new release and are considering the migration. 

BTW, I don't understand the new version numbering scheme: 19 if for the year but what about the second figure? is it incremented each time there is a batch of new features/improvements? is this on a monthly basis? I also see that previous stable branches get fixes, how long are they supported?

**Comment by blinkov** [comment] 2019-06-13 03:58
> is it incremented each time there is a batch of new features/improvements?
@bgranvea yes, second number increases with new features and third one with additional bugfixes

**Comment by alexey-milovidov** [comment] 2019-07-05 11:28
It wasn't backported, but @stavrolia will take a look, maybe it's possible to backport to 19.7.

**Comment by stavrolia** [comment] 2019-07-05 20:11
Done

**Closed** 2019-07-05 21:06 UTC
Labels: already fixed, bug, duplicate
