### ISSUE TITLE
Add column renaming functionality in DDL

### ISSUE THREAD

**Issue by alex-zaitsev** [yandex/ClickHouse#3243] opened 2018-09-28 07:37 UTC
Syntax options:

1. ALTER TABLE table_name RENAME COLUMN old_name TO new_name
2. ALTER TABLE table_name CHANGE COLUMN old_name TO new_name

I personally prefer #1, though MySQL uses #2.

**Comment by perez1987** [comment] 2018-09-28 07:55
I prefer first option

**Comment by vpanfilov** [comment] 2018-10-09 14:05
It is a duplicate of https://github.com/yandex/ClickHouse/issues/146

**Closed** 2019-06-11 21:43 UTC
Labels: duplicate

**Comment by filimonov** [comment] 2020-04-21 22:47
Fixed in #9948
