### ISSUE TITLE
Dropping kafka materialized view freezes until messages committed

### ISSUE THREAD

**Issue by daledude** [yandex/ClickHouse#4308] opened 2019-02-07 19:41 UTC
ClickHouse server version 19.1.6
Ubuntu 16.04.5 LTS

When I "DROP TABLE" a materialized view attached to a kafka queue the command will freeze for as long as it takes to commit messages from the queue. It cannot be killed/aborted.

There is essentially a second part but I'm testing the per kafka queue kafka_max_block_size. The queue only commits every 65536 messages. Queue traffic is about 70 messages a second. Is the 65536 number directly related to max_block_size? Unless I'm missing something it would be block size vs number of messages which doesn't make sense.
```
Once I see this message in the log the DROP TABLE completes.
StorageKafka (monitoring_middle_kafka_queue): Committing 65536 messages
```
```
┌─name─────────────────────┬─value───┬─changed─┬─description───────────────────────────────────────────────────────────────────────────────┐
│ max_block_size           │ 65536   │       0 │ Maximum block size for reading                                                            │
│ max_insert_block_size    │ 1048576 │       0 │ The maximum block size for insertion, if we control the creation of blocks for insertion. │
│ stream_flush_interval_ms │ 7500    │       0 │ Timeout for flushing data from streaming storages.                                        │
└──────────────────────────┴─────────┴─────────┴───────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by daledude** [comment] 2019-02-07 22:56
Setting kafka_max_block_size per kafka table does keep the data flowing through the materialized view.

The problem of waiting for the queue to fill and be written also prevents clickhouse from being shut down. Ultimately the init script does a hard kill of clickhouse because it's waiting for the queue to fill.

**Comment by daledude** [comment] 2019-02-07 23:01
btw, in my case a few queues would take about 15 minutes to "fill" and be committed. So, thats 15 minutes the DROP and a shutdown (hard kill happens before this time, however) would "freeze."

**Comment by kmatt** [comment] 2019-02-22 15:56
I'm wondering if this was the cause of #4282

**Comment by daledude** [comment] 2019-02-22 16:07
I was having the hang problem with 18.14.18 and 18.14.19 as well. The queues would commit quickly though with those versions. I'll give v19.3.3 a shot.

**Comment by abyss7** [comment] 2019-05-15 12:24
From v19.8+ the shutdown and `DROP TABLE` should wait only for `stream_flush_interval_ms` time - is it fair enough?

**Comment by abyss7** [comment] 2019-06-03 15:07
Closing for now.

**Closed by abyss7** 2019-06-03 15:07 UTC
Labels: bug, comp-kafka, need info, v19.1
